/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ActionRowComponentResponseComponentsInner {
    ButtonComponentResponse(Box<models::ButtonComponentResponse>),
    ChannelSelectComponentResponse(Box<models::ChannelSelectComponentResponse>),
    MentionableSelectComponentResponse(Box<models::MentionableSelectComponentResponse>),
    RoleSelectComponentResponse(Box<models::RoleSelectComponentResponse>),
    StringSelectComponentResponse(Box<models::StringSelectComponentResponse>),
    TextInputComponentResponse(Box<models::TextInputComponentResponse>),
    UserSelectComponentResponse(Box<models::UserSelectComponentResponse>),
}

impl Default for ActionRowComponentResponseComponentsInner {
    fn default() -> Self {
        Self::ButtonComponentResponse(Default::default())
    }
}

