/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ActionRowComponentForMessageRequestComponentsInner {
    ButtonComponentForMessageRequest(Box<models::ButtonComponentForMessageRequest>),
    ChannelSelectComponentForMessageRequest(Box<models::ChannelSelectComponentForMessageRequest>),
    MentionableSelectComponentForMessageRequest(Box<models::MentionableSelectComponentForMessageRequest>),
    RoleSelectComponentForMessageRequest(Box<models::RoleSelectComponentForMessageRequest>),
    StringSelectComponentForMessageRequest(Box<models::StringSelectComponentForMessageRequest>),
    UserSelectComponentForMessageRequest(Box<models::UserSelectComponentForMessageRequest>),
}

impl Default for ActionRowComponentForMessageRequestComponentsInner {
    fn default() -> Self {
        Self::ButtonComponentForMessageRequest(Default::default())
    }
}

