/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AddGroupDmUser201Response {
    PrivateChannelResponse(Box<models::PrivateChannelResponse>),
    PrivateGroupChannelResponse(Box<models::PrivateGroupChannelResponse>),
}

impl Default for AddGroupDmUser201Response {
    fn default() -> Self {
        Self::PrivateChannelResponse(Default::default())
    }
}

