/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandNumberOption {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_localizations", skip_serializing_if = "Option::is_none")]
    pub name_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "description_localizations", skip_serializing_if = "Option::is_none")]
    pub description_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "required", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub required: Option<Option<bool>>,
    #[serde(rename = "autocomplete", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub autocomplete: Option<Option<bool>>,
    #[serde(rename = "choices", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub choices: Option<Option<Vec<models::ApplicationCommandOptionNumberChoice>>>,
    #[serde(rename = "min_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_value: Option<Option<f64>>,
    #[serde(rename = "max_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_value: Option<Option<f64>>,
}

impl ApplicationCommandNumberOption {
    pub fn new(r#type: i32, name: String, description: String) -> ApplicationCommandNumberOption {
        ApplicationCommandNumberOption {
            r#type,
            name,
            name_localizations: None,
            description,
            description_localizations: None,
            required: None,
            autocomplete: None,
            choices: None,
            min_value: None,
            max_value: None,
        }
    }
}

