/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandStringOption {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_localizations", skip_serializing_if = "Option::is_none")]
    pub name_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "description_localizations", skip_serializing_if = "Option::is_none")]
    pub description_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "required", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub required: Option<Option<bool>>,
    #[serde(rename = "autocomplete", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub autocomplete: Option<Option<bool>>,
    #[serde(rename = "min_length", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_length: Option<Option<i32>>,
    #[serde(rename = "max_length", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_length: Option<Option<i32>>,
    #[serde(rename = "choices", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub choices: Option<Option<Vec<models::ApplicationCommandOptionStringChoice>>>,
}

impl ApplicationCommandStringOption {
    pub fn new(r#type: i32, name: String, description: String) -> ApplicationCommandStringOption {
        ApplicationCommandStringOption {
            r#type,
            name,
            name_localizations: None,
            description,
            description_localizations: None,
            required: None,
            autocomplete: None,
            min_length: None,
            max_length: None,
            choices: None,
        }
    }
}

