/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationUserRoleConnectionResponse {
    #[serde(rename = "platform_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub platform_name: Option<Option<String>>,
    #[serde(rename = "platform_username", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub platform_username: Option<Option<String>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
}

impl ApplicationUserRoleConnectionResponse {
    pub fn new() -> ApplicationUserRoleConnectionResponse {
        ApplicationUserRoleConnectionResponse {
            platform_name: None,
            platform_username: None,
            metadata: None,
        }
    }
}

