/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandAutocompleteCallbackRequestData {
    #[serde(rename = "choices", skip_serializing_if = "Option::is_none")]
    pub choices: Option<Vec<models::ApplicationCommandOptionStringChoice>>,
}

impl ApplicationCommandAutocompleteCallbackRequestData {
    pub fn new() -> ApplicationCommandAutocompleteCallbackRequestData {
        ApplicationCommandAutocompleteCallbackRequestData {
            choices: None,
        }
    }
}

