/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationFormPartial {
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<Box<models::ApplicationFormPartialDescription>>,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "cover_image", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cover_image: Option<Option<String>>,
    #[serde(rename = "team_id", skip_serializing_if = "Option::is_none")]
    pub team_id: Option<String>,
    #[serde(rename = "flags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Option<i32>>,
    #[serde(rename = "interactions_endpoint_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub interactions_endpoint_url: Option<Option<String>>,
    #[serde(rename = "explicit_content_filter", skip_serializing_if = "Option::is_none")]
    pub explicit_content_filter: Option<i32>,
    #[serde(rename = "max_participants", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_participants: Option<Option<i32>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<i32>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<String>>>,
    #[serde(rename = "custom_install_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_install_url: Option<Option<String>>,
    #[serde(rename = "install_params", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub install_params: Option<Option<Box<models::ApplicationOAuth2InstallParams>>>,
    #[serde(rename = "role_connections_verification_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_connections_verification_url: Option<Option<String>>,
    #[serde(rename = "integration_types_config", skip_serializing_if = "Option::is_none")]
    pub integration_types_config: Option<std::collections::HashMap<String, models::ApplicationFormPartialIntegrationTypesConfigValue>>,
}

impl ApplicationFormPartial {
    pub fn new() -> ApplicationFormPartial {
        ApplicationFormPartial {
            description: None,
            icon: None,
            cover_image: None,
            team_id: None,
            flags: None,
            interactions_endpoint_url: None,
            explicit_content_filter: None,
            max_participants: None,
            r#type: None,
            tags: None,
            custom_install_url: None,
            install_params: None,
            role_connections_verification_url: None,
            integration_types_config: None,
        }
    }
}

