/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationIntegrationTypeConfiguration {
    #[serde(rename = "oauth2_install_params", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub oauth2_install_params: Option<Option<Box<models::ApplicationOAuth2InstallParams>>>,
}

impl ApplicationIntegrationTypeConfiguration {
    pub fn new() -> ApplicationIntegrationTypeConfiguration {
        ApplicationIntegrationTypeConfiguration {
            oauth2_install_params: None,
        }
    }
}

