/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApplicationCommandResponseOptionsInner {
    ApplicationCommandAttachmentOptionResponse(Box<models::ApplicationCommandAttachmentOptionResponse>),
    ApplicationCommandBooleanOptionResponse(Box<models::ApplicationCommandBooleanOptionResponse>),
    ApplicationCommandChannelOptionResponse(Box<models::ApplicationCommandChannelOptionResponse>),
    ApplicationCommandIntegerOptionResponse(Box<models::ApplicationCommandIntegerOptionResponse>),
    ApplicationCommandMentionableOptionResponse(Box<models::ApplicationCommandMentionableOptionResponse>),
    ApplicationCommandNumberOptionResponse(Box<models::ApplicationCommandNumberOptionResponse>),
    ApplicationCommandRoleOptionResponse(Box<models::ApplicationCommandRoleOptionResponse>),
    ApplicationCommandStringOptionResponse(Box<models::ApplicationCommandStringOptionResponse>),
    ApplicationCommandSubcommandGroupOptionResponse(Box<models::ApplicationCommandSubcommandGroupOptionResponse>),
    ApplicationCommandSubcommandOptionResponse(Box<models::ApplicationCommandSubcommandOptionResponse>),
    ApplicationCommandUserOptionResponse(Box<models::ApplicationCommandUserOptionResponse>),
}

impl Default for ApplicationCommandResponseOptionsInner {
    fn default() -> Self {
        Self::ApplicationCommandAttachmentOptionResponse(Default::default())
    }
}

