/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandInteractionMetadataResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserResponse>>,
    #[serde(rename = "authorizing_integration_owners")]
    pub authorizing_integration_owners: std::collections::HashMap<String, String>,
    #[serde(rename = "original_response_message_id", skip_serializing_if = "Option::is_none")]
    pub original_response_message_id: Option<String>,
    #[serde(rename = "target_user", skip_serializing_if = "Option::is_none")]
    pub target_user: Option<Box<models::UserResponse>>,
    #[serde(rename = "target_message_id", skip_serializing_if = "Option::is_none")]
    pub target_message_id: Option<String>,
}

impl ApplicationCommandInteractionMetadataResponse {
    pub fn new(id: String, r#type: i32, authorizing_integration_owners: std::collections::HashMap<String, String>) -> ApplicationCommandInteractionMetadataResponse {
        ApplicationCommandInteractionMetadataResponse {
            id,
            r#type,
            user: None,
            authorizing_integration_owners,
            original_response_message_id: None,
            target_user: None,
            target_message_id: None,
        }
    }
}

