/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandOptionNumberChoiceResponse {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_localized", skip_serializing_if = "Option::is_none")]
    pub name_localized: Option<String>,
    #[serde(rename = "name_localizations", skip_serializing_if = "Option::is_none")]
    pub name_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "value")]
    pub value: f64,
}

impl ApplicationCommandOptionNumberChoiceResponse {
    pub fn new(name: String, value: f64) -> ApplicationCommandOptionNumberChoiceResponse {
        ApplicationCommandOptionNumberChoiceResponse {
            name,
            name_localized: None,
            name_localizations: None,
            value,
        }
    }
}

