/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationOAuth2InstallParamsResponse {
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "permissions")]
    pub permissions: String,
}

impl ApplicationOAuth2InstallParamsResponse {
    pub fn new(scopes: Vec<String>, permissions: String) -> ApplicationOAuth2InstallParamsResponse {
        ApplicationOAuth2InstallParamsResponse {
            scopes,
            permissions,
        }
    }
}

