/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandPatchRequestPartial {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "name_localizations", skip_serializing_if = "Option::is_none")]
    pub name_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "description_localizations", skip_serializing_if = "Option::is_none")]
    pub description_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "options", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub options: Option<Option<Vec<models::ApplicationCommandCreateRequestOptionsInner>>>,
    #[serde(rename = "default_member_permissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_member_permissions: Option<Option<i32>>,
    #[serde(rename = "dm_permission", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub dm_permission: Option<Option<bool>>,
    #[serde(rename = "contexts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contexts: Option<Option<Vec<i32>>>,
    #[serde(rename = "integration_types", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub integration_types: Option<Option<Vec<i32>>>,
    #[serde(rename = "handler", skip_serializing_if = "Option::is_none")]
    pub handler: Option<i32>,
}

impl ApplicationCommandPatchRequestPartial {
    pub fn new() -> ApplicationCommandPatchRequestPartial {
        ApplicationCommandPatchRequestPartial {
            name: None,
            name_localizations: None,
            description: None,
            description_localizations: None,
            options: None,
            default_member_permissions: None,
            dm_permission: None,
            contexts: None,
            integration_types: None,
            handler: None,
        }
    }
}

