/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<i32>>,
    #[serde(rename = "cover_image", skip_serializing_if = "Option::is_none")]
    pub cover_image: Option<String>,
    #[serde(rename = "primary_sku_id", skip_serializing_if = "Option::is_none")]
    pub primary_sku_id: Option<String>,
    #[serde(rename = "bot", skip_serializing_if = "Option::is_none")]
    pub bot: Option<Box<models::UserResponse>>,
    #[serde(rename = "slug", skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "guild_id", skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<String>,
    #[serde(rename = "rpc_origins", skip_serializing_if = "Option::is_none")]
    pub rpc_origins: Option<Vec<String>>,
    #[serde(rename = "bot_public", skip_serializing_if = "Option::is_none")]
    pub bot_public: Option<bool>,
    #[serde(rename = "bot_require_code_grant", skip_serializing_if = "Option::is_none")]
    pub bot_require_code_grant: Option<bool>,
    #[serde(rename = "terms_of_service_url", skip_serializing_if = "Option::is_none")]
    pub terms_of_service_url: Option<String>,
    #[serde(rename = "privacy_policy_url", skip_serializing_if = "Option::is_none")]
    pub privacy_policy_url: Option<String>,
    #[serde(rename = "custom_install_url", skip_serializing_if = "Option::is_none")]
    pub custom_install_url: Option<String>,
    #[serde(rename = "install_params", skip_serializing_if = "Option::is_none")]
    pub install_params: Option<Box<models::ApplicationOAuth2InstallParamsResponse>>,
    #[serde(rename = "integration_types_config", skip_serializing_if = "Option::is_none")]
    pub integration_types_config: Option<std::collections::HashMap<String, models::ApplicationIntegrationTypeConfigurationResponse>>,
    #[serde(rename = "verify_key")]
    pub verify_key: String,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "max_participants", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_participants: Option<Option<i32>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl ApplicationResponse {
    pub fn new(id: String, name: String, description: String, verify_key: String, flags: i32) -> ApplicationResponse {
        ApplicationResponse {
            id,
            name,
            icon: None,
            description,
            r#type: None,
            cover_image: None,
            primary_sku_id: None,
            bot: None,
            slug: None,
            guild_id: None,
            rpc_origins: None,
            bot_public: None,
            bot_require_code_grant: None,
            terms_of_service_url: None,
            privacy_policy_url: None,
            custom_install_url: None,
            install_params: None,
            integration_types_config: None,
            verify_key,
            flags,
            max_participants: None,
            tags: None,
        }
    }
}

