/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApplicationCommandCreateRequestOptionsInner {
    ApplicationCommandAttachmentOption(Box<models::ApplicationCommandAttachmentOption>),
    ApplicationCommandBooleanOption(Box<models::ApplicationCommandBooleanOption>),
    ApplicationCommandChannelOption(Box<models::ApplicationCommandChannelOption>),
    ApplicationCommandIntegerOption(Box<models::ApplicationCommandIntegerOption>),
    ApplicationCommandMentionableOption(Box<models::ApplicationCommandMentionableOption>),
    ApplicationCommandNumberOption(Box<models::ApplicationCommandNumberOption>),
    ApplicationCommandRoleOption(Box<models::ApplicationCommandRoleOption>),
    ApplicationCommandStringOption(Box<models::ApplicationCommandStringOption>),
    ApplicationCommandSubcommandGroupOption(Box<models::ApplicationCommandSubcommandGroupOption>),
    ApplicationCommandSubcommandOption(Box<models::ApplicationCommandSubcommandOption>),
    ApplicationCommandUserOption(Box<models::ApplicationCommandUserOption>),
}

impl Default for ApplicationCommandCreateRequestOptionsInner {
    fn default() -> Self {
        Self::ApplicationCommandAttachmentOption(Default::default())
    }
}

