/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandIntegerOptionResponse {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_localized", skip_serializing_if = "Option::is_none")]
    pub name_localized: Option<String>,
    #[serde(rename = "name_localizations", skip_serializing_if = "Option::is_none")]
    pub name_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "description_localized", skip_serializing_if = "Option::is_none")]
    pub description_localized: Option<String>,
    #[serde(rename = "description_localizations", skip_serializing_if = "Option::is_none")]
    pub description_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    #[serde(rename = "autocomplete", skip_serializing_if = "Option::is_none")]
    pub autocomplete: Option<bool>,
    #[serde(rename = "choices", skip_serializing_if = "Option::is_none")]
    pub choices: Option<Vec<models::ApplicationCommandOptionIntegerChoiceResponse>>,
    #[serde(rename = "min_value", skip_serializing_if = "Option::is_none")]
    pub min_value: Option<i64>,
    #[serde(rename = "max_value", skip_serializing_if = "Option::is_none")]
    pub max_value: Option<i64>,
}

impl ApplicationCommandIntegerOptionResponse {
    pub fn new(r#type: i32, name: String, description: String) -> ApplicationCommandIntegerOptionResponse {
        ApplicationCommandIntegerOptionResponse {
            r#type,
            name,
            name_localized: None,
            name_localizations: None,
            description,
            description_localized: None,
            description_localizations: None,
            required: None,
            autocomplete: None,
            choices: None,
            min_value: None,
            max_value: None,
        }
    }
}

