/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ApplicationFormPartialIntegrationTypesConfigValue {
    ApplicationIntegrationTypeConfiguration(Box<models::ApplicationIntegrationTypeConfiguration>),
}

impl Default for ApplicationFormPartialIntegrationTypesConfigValue {
    fn default() -> Self {
        Self::ApplicationIntegrationTypeConfiguration(Default::default())
    }
}

