/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandAutocompleteCallbackRequest {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<i32>,
    #[serde(rename = "data")]
    pub data: Box<models::ApplicationCommandAutocompleteCallbackRequestData>,
}

impl ApplicationCommandAutocompleteCallbackRequest {
    pub fn new(r#type: Option<i32>, data: models::ApplicationCommandAutocompleteCallbackRequestData) -> ApplicationCommandAutocompleteCallbackRequest {
        ApplicationCommandAutocompleteCallbackRequest {
            r#type,
            data: Box::new(data),
        }
    }
}

