/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandPermission {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "permission")]
    pub permission: bool,
}

impl ApplicationCommandPermission {
    pub fn new(id: String, r#type: i32, permission: bool) -> ApplicationCommandPermission {
        ApplicationCommandPermission {
            id,
            r#type,
            permission,
        }
    }
}

