/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationFormPartialDescription {
    #[serde(rename = "default")]
    pub default: String,
    #[serde(rename = "localizations", skip_serializing_if = "Option::is_none")]
    pub localizations: Option<std::collections::HashMap<String, String>>,
}

impl ApplicationFormPartialDescription {
    pub fn new(default: String) -> ApplicationFormPartialDescription {
        ApplicationFormPartialDescription {
            default,
            localizations: None,
        }
    }
}

