/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationCommandAttachmentOption {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "name_localizations", skip_serializing_if = "Option::is_none")]
    pub name_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "description_localizations", skip_serializing_if = "Option::is_none")]
    pub description_localizations: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "required", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub required: Option<Option<bool>>,
}

impl ApplicationCommandAttachmentOption {
    pub fn new(r#type: i32, name: String, description: String) -> ApplicationCommandAttachmentOption {
        ApplicationCommandAttachmentOption {
            r#type,
            name,
            name_localizations: None,
            description,
            description_localizations: None,
            required: None,
        }
    }
}

