/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditLogEntryResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "action_type", deserialize_with = "Option::deserialize")]
    pub action_type: Option<i32>,
    #[serde(rename = "user_id", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    #[serde(rename = "target_id", skip_serializing_if = "Option::is_none")]
    pub target_id: Option<String>,
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<Vec<models::AuditLogObjectChangeResponse>>,
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl AuditLogEntryResponse {
    pub fn new(id: String, action_type: Option<i32>) -> AuditLogEntryResponse {
        AuditLogEntryResponse {
            id,
            action_type,
            user_id: None,
            target_id: None,
            changes: None,
            options: None,
            reason: None,
        }
    }
}

