/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuditLogObjectChangeResponse {
    #[serde(rename = "key", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub key: Option<Option<String>>,
    #[serde(rename = "new_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub new_value: Option<Option<serde_json::Value>>,
    #[serde(rename = "old_value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub old_value: Option<Option<serde_json::Value>>,
}

impl AuditLogObjectChangeResponse {
    pub fn new() -> AuditLogObjectChangeResponse {
        AuditLogObjectChangeResponse {
            key: None,
            new_value: None,
            old_value: None,
        }
    }
}

