/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BanUserFromGuildRequest {
    #[serde(rename = "delete_message_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delete_message_seconds: Option<Option<i32>>,
    #[serde(rename = "delete_message_days", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delete_message_days: Option<Option<i32>>,
}

impl BanUserFromGuildRequest {
    pub fn new() -> BanUserFromGuildRequest {
        BanUserFromGuildRequest {
            delete_message_seconds: None,
            delete_message_days: None,
        }
    }
}

