/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BaseCreateMessageCreateRequestComponentsInner {
    ActionRowComponentForMessageRequest(Box<models::ActionRowComponentForMessageRequest>),
    ContainerComponentForMessageRequest(Box<models::ContainerComponentForMessageRequest>),
    FileComponentForMessageRequest(Box<models::FileComponentForMessageRequest>),
    MediaGalleryComponentForMessageRequest(Box<models::MediaGalleryComponentForMessageRequest>),
    SectionComponentForMessageRequest(Box<models::SectionComponentForMessageRequest>),
    SeparatorComponentForMessageRequest(Box<models::SeparatorComponentForMessageRequest>),
    TextDisplayComponentForMessageRequest(Box<models::TextDisplayComponentForMessageRequest>),
}

impl Default for BaseCreateMessageCreateRequestComponentsInner {
    fn default() -> Self {
        Self::ActionRowComponentForMessageRequest(Default::default())
    }
}

