/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BasicMessageResponse {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "mentions")]
    pub mentions: Vec<models::UserResponse>,
    #[serde(rename = "mention_roles")]
    pub mention_roles: Vec<String>,
    #[serde(rename = "attachments")]
    pub attachments: Vec<models::MessageAttachmentResponse>,
    #[serde(rename = "embeds")]
    pub embeds: Vec<models::MessageEmbedResponse>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "edited_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub edited_timestamp: Option<Option<String>>,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "components")]
    pub components: Vec<models::BasicMessageResponseComponentsInner>,
    #[serde(rename = "stickers", skip_serializing_if = "Option::is_none")]
    pub stickers: Option<Vec<models::GetSticker200Response>>,
    #[serde(rename = "sticker_items", skip_serializing_if = "Option::is_none")]
    pub sticker_items: Option<Vec<models::MessageStickerItemResponse>>,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "author")]
    pub author: Box<models::UserResponse>,
    #[serde(rename = "pinned")]
    pub pinned: bool,
    #[serde(rename = "mention_everyone")]
    pub mention_everyone: bool,
    #[serde(rename = "tts")]
    pub tts: bool,
    #[serde(rename = "call", skip_serializing_if = "Option::is_none")]
    pub call: Option<Box<models::MessageCallResponse>>,
    #[serde(rename = "activity", skip_serializing_if = "Option::is_none")]
    pub activity: Option<serde_json::Value>,
    #[serde(rename = "application", skip_serializing_if = "Option::is_none")]
    pub application: Option<Box<models::BasicApplicationResponse>>,
    #[serde(rename = "application_id", skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
    #[serde(rename = "interaction", skip_serializing_if = "Option::is_none")]
    pub interaction: Option<Box<models::MessageInteractionResponse>>,
    #[serde(rename = "nonce", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<Option<Box<models::BasicMessageResponseNonce>>>,
    #[serde(rename = "webhook_id", skip_serializing_if = "Option::is_none")]
    pub webhook_id: Option<String>,
    #[serde(rename = "message_reference", skip_serializing_if = "Option::is_none")]
    pub message_reference: Option<Box<models::MessageReferenceResponse>>,
    #[serde(rename = "thread", skip_serializing_if = "Option::is_none")]
    pub thread: Option<Box<models::ThreadResponse>>,
    #[serde(rename = "mention_channels", skip_serializing_if = "Option::is_none")]
    pub mention_channels: Option<Vec<models::MessageMentionChannelResponse>>,
    #[serde(rename = "role_subscription_data", skip_serializing_if = "Option::is_none")]
    pub role_subscription_data: Option<Box<models::MessageRoleSubscriptionDataResponse>>,
    #[serde(rename = "purchase_notification", skip_serializing_if = "Option::is_none")]
    pub purchase_notification: Option<Box<models::PurchaseNotificationResponse>>,
    #[serde(rename = "position", skip_serializing_if = "Option::is_none")]
    pub position: Option<i32>,
    #[serde(rename = "resolved", skip_serializing_if = "Option::is_none")]
    pub resolved: Option<Box<models::ResolvedObjectsResponse>>,
    #[serde(rename = "poll", skip_serializing_if = "Option::is_none")]
    pub poll: Option<Box<models::PollResponse>>,
    #[serde(rename = "shared_client_theme", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shared_client_theme: Option<Option<Box<models::CustomClientThemeResponse>>>,
    #[serde(rename = "interaction_metadata", skip_serializing_if = "Option::is_none")]
    pub interaction_metadata: Option<Box<models::BasicMessageResponseInteractionMetadata>>,
    #[serde(rename = "message_snapshots", skip_serializing_if = "Option::is_none")]
    pub message_snapshots: Option<Vec<models::MessageSnapshotResponse>>,
}

impl BasicMessageResponse {
    pub fn new(r#type: i32, content: String, mentions: Vec<models::UserResponse>, mention_roles: Vec<String>, attachments: Vec<models::MessageAttachmentResponse>, embeds: Vec<models::MessageEmbedResponse>, timestamp: String, flags: i32, components: Vec<models::BasicMessageResponseComponentsInner>, id: String, channel_id: String, author: models::UserResponse, pinned: bool, mention_everyone: bool, tts: bool) -> BasicMessageResponse {
        BasicMessageResponse {
            r#type,
            content,
            mentions,
            mention_roles,
            attachments,
            embeds,
            timestamp,
            edited_timestamp: None,
            flags,
            components,
            stickers: None,
            sticker_items: None,
            id,
            channel_id,
            author: Box::new(author),
            pinned,
            mention_everyone,
            tts,
            call: None,
            activity: None,
            application: None,
            application_id: None,
            interaction: None,
            nonce: None,
            webhook_id: None,
            message_reference: None,
            thread: None,
            mention_channels: None,
            role_subscription_data: None,
            purchase_notification: None,
            position: None,
            resolved: None,
            poll: None,
            shared_client_theme: None,
            interaction_metadata: None,
            message_snapshots: None,
        }
    }
}

