/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum BasicMessageResponseComponentsInner {
    ActionRowComponentResponse(Box<models::ActionRowComponentResponse>),
    ContainerComponentResponse(Box<models::ContainerComponentResponse>),
    FileComponentResponse(Box<models::FileComponentResponse>),
    MediaGalleryComponentResponse(Box<models::MediaGalleryComponentResponse>),
    SectionComponentResponse(Box<models::SectionComponentResponse>),
    SeparatorComponentResponse(Box<models::SeparatorComponentResponse>),
    TextDisplayComponentResponse(Box<models::TextDisplayComponentResponse>),
}

impl Default for BasicMessageResponseComponentsInner {
    fn default() -> Self {
        Self::ActionRowComponentResponse(Default::default())
    }
}

