/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockMessageActionMetadataResponse {
    #[serde(rename = "custom_message", skip_serializing_if = "Option::is_none")]
    pub custom_message: Option<String>,
}

impl BlockMessageActionMetadataResponse {
    pub fn new() -> BlockMessageActionMetadataResponse {
        BlockMessageActionMetadataResponse {
            custom_message: None,
        }
    }
}

