/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockMessageAction {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<Box<models::BlockMessageActionMetadata>>>,
}

impl BlockMessageAction {
    pub fn new(r#type: i32) -> BlockMessageAction {
        BlockMessageAction {
            r#type,
            metadata: None,
        }
    }
}

