/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockMessageActionResponse {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::BlockMessageActionMetadataResponse>,
}

impl BlockMessageActionResponse {
    pub fn new(r#type: i32, metadata: models::BlockMessageActionMetadataResponse) -> BlockMessageActionResponse {
        BlockMessageActionResponse {
            r#type,
            metadata: Box::new(metadata),
        }
    }
}

