/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BotPartnerSdkTokenRequest {
    #[serde(rename = "external_user_id")]
    pub external_user_id: String,
    #[serde(rename = "preferred_global_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub preferred_global_name: Option<Option<String>>,
}

impl BotPartnerSdkTokenRequest {
    pub fn new(external_user_id: String) -> BotPartnerSdkTokenRequest {
        BotPartnerSdkTokenRequest {
            external_user_id,
            preferred_global_name: None,
        }
    }
}

