/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BotPartnerSdkUnmergeProvisionalAccountRequest {
    #[serde(rename = "external_user_id")]
    pub external_user_id: String,
}

impl BotPartnerSdkUnmergeProvisionalAccountRequest {
    pub fn new(external_user_id: String) -> BotPartnerSdkUnmergeProvisionalAccountRequest {
        BotPartnerSdkUnmergeProvisionalAccountRequest {
            external_user_id,
        }
    }
}

