/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkUpdateGuildChannelsRequestInner {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "position", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub position: Option<Option<i32>>,
    #[serde(rename = "parent_id", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "lock_permissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub lock_permissions: Option<Option<bool>>,
}

impl BulkUpdateGuildChannelsRequestInner {
    pub fn new() -> BulkUpdateGuildChannelsRequestInner {
        BulkUpdateGuildChannelsRequestInner {
            id: None,
            position: None,
            parent_id: None,
            lock_permissions: None,
        }
    }
}

