/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkBanUsersResponse {
    #[serde(rename = "banned_users")]
    pub banned_users: Vec<String>,
    #[serde(rename = "failed_users")]
    pub failed_users: Vec<String>,
}

impl BulkBanUsersResponse {
    pub fn new(banned_users: Vec<String>, failed_users: Vec<String>) -> BulkBanUsersResponse {
        BulkBanUsersResponse {
            banned_users,
            failed_users,
        }
    }
}

