/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BulkLobbyMemberRequest {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "flags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Option<Flags>>,
    #[serde(rename = "remove_member", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub remove_member: Option<Option<bool>>,
}

impl BulkLobbyMemberRequest {
    pub fn new(id: String) -> BulkLobbyMemberRequest {
        BulkLobbyMemberRequest {
            id,
            metadata: None,
            flags: None,
            remove_member: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Flags {
    #[serde(rename = "1")]
    Variant1,
}

impl Default for Flags {
    fn default() -> Flags {
        Self::Variant1
    }
}

