/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelSelectComponentResponse {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "custom_id")]
    pub custom_id: String,
    #[serde(rename = "placeholder", skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<String>,
    #[serde(rename = "min_values", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_values: Option<Option<i32>>,
    #[serde(rename = "max_values", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_values: Option<Option<i32>>,
    #[serde(rename = "disabled", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<bool>,
    #[serde(rename = "channel_types", skip_serializing_if = "Option::is_none")]
    pub channel_types: Option<Vec<i32>>,
    #[serde(rename = "default_values", skip_serializing_if = "Option::is_none")]
    pub default_values: Option<Vec<models::ChannelSelectDefaultValueResponse>>,
}

impl ChannelSelectComponentResponse {
    pub fn new(r#type: i32, id: i32, custom_id: String) -> ChannelSelectComponentResponse {
        ChannelSelectComponentResponse {
            r#type,
            id,
            custom_id,
            placeholder: None,
            min_values: None,
            max_values: None,
            disabled: None,
            channel_types: None,
            default_values: None,
        }
    }
}

