/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelPermissionOverwriteRequest {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<i32>>,
    #[serde(rename = "allow", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allow: Option<Option<i32>>,
    #[serde(rename = "deny", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deny: Option<Option<i32>>,
}

impl ChannelPermissionOverwriteRequest {
    pub fn new(id: String) -> ChannelPermissionOverwriteRequest {
        ChannelPermissionOverwriteRequest {
            id,
            r#type: None,
            allow: None,
            deny: None,
        }
    }
}

