/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelPermissionOverwriteResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<i32>,
    #[serde(rename = "allow")]
    pub allow: String,
    #[serde(rename = "deny")]
    pub deny: String,
}

impl ChannelPermissionOverwriteResponse {
    pub fn new(id: String, r#type: Option<i32>, allow: String, deny: String) -> ChannelPermissionOverwriteResponse {
        ChannelPermissionOverwriteResponse {
            id,
            r#type,
            allow,
            deny,
        }
    }
}

