/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChannelSelectDefaultValueResponse {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<String>,
    #[serde(rename = "id")]
    pub id: String,
}

impl ChannelSelectDefaultValueResponse {
    pub fn new(r#type: Option<String>, id: String) -> ChannelSelectDefaultValueResponse {
        ChannelSelectDefaultValueResponse {
            r#type,
            id,
        }
    }
}

