/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandPermissionsResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "application_id")]
    pub application_id: String,
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "permissions")]
    pub permissions: Vec<models::CommandPermissionResponse>,
}

impl CommandPermissionsResponse {
    pub fn new(id: String, application_id: String, guild_id: String, permissions: Vec<models::CommandPermissionResponse>) -> CommandPermissionsResponse {
        CommandPermissionsResponse {
            id,
            application_id,
            guild_id,
            permissions,
        }
    }
}

