/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedAccountIntegrationResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<String>,
    #[serde(rename = "account")]
    pub account: Box<models::AccountResponse>,
    #[serde(rename = "guild")]
    pub guild: Box<models::ConnectedAccountGuildResponse>,
}

impl ConnectedAccountIntegrationResponse {
    pub fn new(id: String, r#type: Option<String>, account: models::AccountResponse, guild: models::ConnectedAccountGuildResponse) -> ConnectedAccountIntegrationResponse {
        ConnectedAccountIntegrationResponse {
            id,
            r#type,
            account: Box::new(account),
            guild: Box::new(guild),
        }
    }
}

