/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedAccountResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<String>,
    #[serde(rename = "friend_sync")]
    pub friend_sync: bool,
    #[serde(rename = "integrations", skip_serializing_if = "Option::is_none")]
    pub integrations: Option<Vec<models::ConnectedAccountIntegrationResponse>>,
    #[serde(rename = "show_activity")]
    pub show_activity: bool,
    #[serde(rename = "two_way_link")]
    pub two_way_link: bool,
    #[serde(rename = "verified")]
    pub verified: bool,
    #[serde(rename = "visibility", deserialize_with = "Option::deserialize")]
    pub visibility: Option<i32>,
    #[serde(rename = "revoked", skip_serializing_if = "Option::is_none")]
    pub revoked: Option<bool>,
}

impl ConnectedAccountResponse {
    pub fn new(id: String, r#type: Option<String>, friend_sync: bool, show_activity: bool, two_way_link: bool, verified: bool, visibility: Option<i32>) -> ConnectedAccountResponse {
        ConnectedAccountResponse {
            id,
            name: None,
            r#type,
            friend_sync,
            integrations: None,
            show_activity,
            two_way_link,
            verified,
            visibility,
            revoked: None,
        }
    }
}

