/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContainerComponentResponse {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "accent_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accent_color: Option<Option<i32>>,
    #[serde(rename = "components")]
    pub components: Vec<models::ContainerComponentResponseComponentsInner>,
    #[serde(rename = "spoiler")]
    pub spoiler: bool,
}

impl ContainerComponentResponse {
    pub fn new(r#type: i32, id: i32, components: Vec<models::ContainerComponentResponseComponentsInner>, spoiler: bool) -> ContainerComponentResponse {
        ContainerComponentResponse {
            r#type,
            id,
            accent_color: None,
            components,
            spoiler,
        }
    }
}

