/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CreateAutoModerationRule200Response {
    DefaultKeywordRuleResponse(Box<models::DefaultKeywordRuleResponse>),
    KeywordRuleResponse(Box<models::KeywordRuleResponse>),
    MlSpamRuleResponse(Box<models::MlSpamRuleResponse>),
    MentionSpamRuleResponse(Box<models::MentionSpamRuleResponse>),
    SpamLinkRuleResponse(Box<models::SpamLinkRuleResponse>),
}

impl Default for CreateAutoModerationRule200Response {
    fn default() -> Self {
        Self::DefaultKeywordRuleResponse(Default::default())
    }
}

