/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateTextThreadWithoutMessageRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "auto_archive_duration", skip_serializing_if = "Option::is_none")]
    pub auto_archive_duration: Option<i32>,
    #[serde(rename = "rate_limit_per_user", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rate_limit_per_user: Option<Option<i32>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<i32>>,
    #[serde(rename = "invitable", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invitable: Option<Option<bool>>,
}

impl CreateTextThreadWithoutMessageRequest {
    pub fn new(name: String) -> CreateTextThreadWithoutMessageRequest {
        CreateTextThreadWithoutMessageRequest {
            name,
            auto_archive_duration: None,
            rate_limit_per_user: None,
            r#type: None,
            invitable: None,
        }
    }
}

