/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateRoleRequest {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "permissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Option<i32>>,
    #[serde(rename = "color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color: Option<Option<i32>>,
    #[serde(rename = "hoist", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub hoist: Option<Option<bool>>,
    #[serde(rename = "mentionable", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mentionable: Option<Option<bool>>,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "unicode_emoji", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unicode_emoji: Option<Option<String>>,
}

impl CreateRoleRequest {
    pub fn new() -> CreateRoleRequest {
        CreateRoleRequest {
            name: None,
            permissions: None,
            color: None,
            hoist: None,
            mentionable: None,
            icon: None,
            unicode_emoji: None,
        }
    }
}

