/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateChannelInviteRequest {
    #[serde(rename = "max_age", skip_serializing_if = "Option::is_none")]
    pub max_age: Option<i32>,
    #[serde(rename = "temporary", skip_serializing_if = "Option::is_none")]
    pub temporary: Option<bool>,
    #[serde(rename = "max_uses", skip_serializing_if = "Option::is_none")]
    pub max_uses: Option<i32>,
    #[serde(rename = "unique", skip_serializing_if = "Option::is_none")]
    pub unique: Option<bool>,
    #[serde(rename = "target_user_id", skip_serializing_if = "Option::is_none")]
    pub target_user_id: Option<String>,
    #[serde(rename = "target_application_id", skip_serializing_if = "Option::is_none")]
    pub target_application_id: Option<String>,
    #[serde(rename = "target_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_type: Option<Option<i32>>,
}

impl CreateChannelInviteRequest {
    pub fn new() -> CreateChannelInviteRequest {
        CreateChannelInviteRequest {
            max_age: None,
            temporary: None,
            max_uses: None,
            unique: None,
            target_user_id: None,
            target_application_id: None,
            target_type: None,
        }
    }
}

