/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMessageInteractionCallbackResponse {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<i32>,
    #[serde(rename = "message")]
    pub message: Box<models::MessageResponse>,
}

impl CreateMessageInteractionCallbackResponse {
    pub fn new(r#type: Option<i32>, message: models::MessageResponse) -> CreateMessageInteractionCallbackResponse {
        CreateMessageInteractionCallbackResponse {
            r#type,
            message: Box::new(message),
        }
    }
}

