/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateThreadRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "auto_archive_duration", skip_serializing_if = "Option::is_none")]
    pub auto_archive_duration: Option<i32>,
    #[serde(rename = "rate_limit_per_user", skip_serializing_if = "Option::is_none")]
    pub rate_limit_per_user: Option<i32>,
    #[serde(rename = "applied_tags", skip_serializing_if = "Option::is_none")]
    pub applied_tags: Option<Vec<String>>,
    #[serde(rename = "message")]
    pub message: Box<models::BaseCreateMessageCreateRequest>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    #[serde(rename = "invitable", skip_serializing_if = "Option::is_none")]
    pub invitable: Option<bool>,
}

impl CreateThreadRequest {
    pub fn new(name: String, message: models::BaseCreateMessageCreateRequest) -> CreateThreadRequest {
        CreateThreadRequest {
            name,
            auto_archive_duration: None,
            rate_limit_per_user: None,
            applied_tags: None,
            message: Box::new(message),
            r#type: None,
            invitable: None,
        }
    }
}

