/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatePrivateChannelRequest {
    #[serde(rename = "recipient_id", skip_serializing_if = "Option::is_none")]
    pub recipient_id: Option<String>,
    #[serde(rename = "access_tokens", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub access_tokens: Option<Option<Vec<String>>>,
    #[serde(rename = "nicks", skip_serializing_if = "Option::is_none")]
    pub nicks: Option<std::collections::HashMap<String, String>>,
}

impl CreatePrivateChannelRequest {
    pub fn new() -> CreatePrivateChannelRequest {
        CreatePrivateChannelRequest {
            recipient_id: None,
            access_tokens: None,
            nicks: None,
        }
    }
}

