/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateLobbyRequest {
    #[serde(rename = "idle_timeout_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub idle_timeout_seconds: Option<Option<i32>>,
    #[serde(rename = "members", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub members: Option<Option<Vec<models::LobbyMemberRequest>>>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "flags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Option<Flags>>,
    #[serde(rename = "override_event_webhooks_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub override_event_webhooks_url: Option<Option<String>>,
}

impl CreateLobbyRequest {
    pub fn new() -> CreateLobbyRequest {
        CreateLobbyRequest {
            idle_timeout_seconds: None,
            members: None,
            metadata: None,
            flags: None,
            override_event_webhooks_url: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Flags {
    #[serde(rename = "1")]
    Variant1,
}

impl Default for Flags {
    fn default() -> Flags {
        Self::Variant1
    }
}

