/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateEntitlementRequestData {
    #[serde(rename = "sku_id")]
    pub sku_id: String,
    #[serde(rename = "owner_id")]
    pub owner_id: String,
    #[serde(rename = "owner_type")]
    pub owner_type: i32,
}

impl CreateEntitlementRequestData {
    pub fn new(sku_id: String, owner_id: String, owner_type: i32) -> CreateEntitlementRequestData {
        CreateEntitlementRequestData {
            sku_id,
            owner_id,
            owner_type,
        }
    }
}

