/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGroupDmInviteRequest {
    #[serde(rename = "max_age", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_age: Option<Option<i32>>,
}

impl CreateGroupDmInviteRequest {
    pub fn new() -> CreateGroupDmInviteRequest {
        CreateGroupDmInviteRequest {
            max_age: None,
        }
    }
}

