/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateStageInstanceRequest {
    #[serde(rename = "topic")]
    pub topic: String,
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "privacy_level", skip_serializing_if = "Option::is_none")]
    pub privacy_level: Option<i32>,
    #[serde(rename = "guild_scheduled_event_id", skip_serializing_if = "Option::is_none")]
    pub guild_scheduled_event_id: Option<String>,
    #[serde(rename = "send_start_notification", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub send_start_notification: Option<Option<bool>>,
}

impl CreateStageInstanceRequest {
    pub fn new(topic: String, channel_id: String) -> CreateStageInstanceRequest {
        CreateStageInstanceRequest {
            topic,
            channel_id,
            privacy_level: None,
            guild_scheduled_event_id: None,
            send_start_notification: None,
        }
    }
}

