/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateMessageInteractionCallbackRequest {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<i32>,
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<Box<models::IncomingWebhookInteractionRequest>>>,
}

impl CreateMessageInteractionCallbackRequest {
    pub fn new(r#type: Option<i32>) -> CreateMessageInteractionCallbackRequest {
        CreateMessageInteractionCallbackRequest {
            r#type,
            data: None,
        }
    }
}

