/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomClientThemeResponse {
    #[serde(rename = "colors")]
    pub colors: Vec<String>,
    #[serde(rename = "gradient_angle")]
    pub gradient_angle: i32,
    #[serde(rename = "base_mix")]
    pub base_mix: i32,
    #[serde(rename = "base_theme")]
    pub base_theme: i32,
}

impl CustomClientThemeResponse {
    pub fn new(colors: Vec<String>, gradient_angle: i32, base_mix: i32, base_theme: i32) -> CustomClientThemeResponse {
        CustomClientThemeResponse {
            colors,
            gradient_angle,
            base_mix,
            base_theme,
        }
    }
}

