/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomClientThemeShareRequest {
    #[serde(rename = "colors")]
    pub colors: Vec<String>,
    #[serde(rename = "gradient_angle")]
    pub gradient_angle: i32,
    #[serde(rename = "base_mix")]
    pub base_mix: i32,
    #[serde(rename = "base_theme", skip_serializing_if = "Option::is_none")]
    pub base_theme: Option<i32>,
}

impl CustomClientThemeShareRequest {
    pub fn new(colors: Vec<String>, gradient_angle: i32, base_mix: i32) -> CustomClientThemeShareRequest {
        CustomClientThemeShareRequest {
            colors,
            gradient_angle,
            base_mix,
            base_theme: None,
        }
    }
}

