/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultKeywordListTriggerMetadata {
    #[serde(rename = "allow_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allow_list: Option<Option<Vec<String>>>,
    #[serde(rename = "presets", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub presets: Option<Option<Vec<i32>>>,
}

impl DefaultKeywordListTriggerMetadata {
    pub fn new() -> DefaultKeywordListTriggerMetadata {
        DefaultKeywordListTriggerMetadata {
            allow_list: None,
            presets: None,
        }
    }
}

