/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DefaultKeywordListTriggerMetadataResponse {
    #[serde(rename = "allow_list")]
    pub allow_list: Vec<String>,
    #[serde(rename = "presets")]
    pub presets: Vec<i32>,
}

impl DefaultKeywordListTriggerMetadataResponse {
    pub fn new(allow_list: Vec<String>, presets: Vec<i32>) -> DefaultKeywordListTriggerMetadataResponse {
        DefaultKeywordListTriggerMetadataResponse {
            allow_list,
            presets,
        }
    }
}

