/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DiscordIntegrationResponse {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<String>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "account")]
    pub account: Box<models::AccountResponse>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "application")]
    pub application: Box<models::IntegrationApplicationResponse>,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserResponse>>,
}

impl DiscordIntegrationResponse {
    pub fn new(r#type: Option<String>, account: models::AccountResponse, enabled: bool, id: String, application: models::IntegrationApplicationResponse, scopes: Vec<String>) -> DiscordIntegrationResponse {
        DiscordIntegrationResponse {
            r#type,
            name: None,
            account: Box::new(account),
            enabled,
            id,
            application: Box::new(application),
            scopes,
            user: None,
        }
    }
}

