/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbeddedActivityInstance {
    #[serde(rename = "application_id")]
    pub application_id: String,
    #[serde(rename = "instance_id")]
    pub instance_id: String,
    #[serde(rename = "launch_id")]
    pub launch_id: String,
    #[serde(rename = "location")]
    pub location: Box<models::EmbeddedActivityInstanceLocation>,
    #[serde(rename = "users")]
    pub users: Vec<String>,
}

impl EmbeddedActivityInstance {
    pub fn new(application_id: String, instance_id: String, launch_id: String, location: models::EmbeddedActivityInstanceLocation, users: Vec<String>) -> EmbeddedActivityInstance {
        EmbeddedActivityInstance {
            application_id,
            instance_id,
            launch_id,
            location: Box::new(location),
            users,
        }
    }
}

