/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum EmbeddedActivityInstanceLocation {
    GuildChannelLocation(Box<models::GuildChannelLocation>),
    PrivateChannelLocation(Box<models::PrivateChannelLocation>),
}

impl Default for EmbeddedActivityInstanceLocation {
    fn default() -> Self {
        Self::GuildChannelLocation(Default::default())
    }
}

