/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmojiResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserResponse>>,
    #[serde(rename = "roles")]
    pub roles: Vec<String>,
    #[serde(rename = "require_colons")]
    pub require_colons: bool,
    #[serde(rename = "managed")]
    pub managed: bool,
    #[serde(rename = "animated")]
    pub animated: bool,
    #[serde(rename = "available")]
    pub available: bool,
}

impl EmojiResponse {
    pub fn new(id: String, name: String, roles: Vec<String>, require_colons: bool, managed: bool, animated: bool, available: bool) -> EmojiResponse {
        EmojiResponse {
            id,
            name,
            user: None,
            roles,
            require_colons,
            managed,
            animated,
            available,
        }
    }
}

