/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntityMetadataExternalResponse {
    #[serde(rename = "location")]
    pub location: String,
}

impl EntityMetadataExternalResponse {
    pub fn new(location: String) -> EntityMetadataExternalResponse {
        EntityMetadataExternalResponse {
            location,
        }
    }
}

