/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EntitlementResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sku_id")]
    pub sku_id: String,
    #[serde(rename = "application_id")]
    pub application_id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "guild_id", skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<String>,
    #[serde(rename = "deleted")]
    pub deleted: bool,
    #[serde(rename = "starts_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub starts_at: Option<Option<String>>,
    #[serde(rename = "ends_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ends_at: Option<Option<String>>,
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<i32>,
    #[serde(rename = "fulfilled_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fulfilled_at: Option<Option<String>>,
    #[serde(rename = "fulfillment_status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fulfillment_status: Option<Option<i32>>,
    #[serde(rename = "consumed", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub consumed: Option<Option<bool>>,
    #[serde(rename = "gifter_user_id", skip_serializing_if = "Option::is_none")]
    pub gifter_user_id: Option<String>,
}

impl EntitlementResponse {
    pub fn new(id: String, sku_id: String, application_id: String, user_id: String, deleted: bool, r#type: Option<i32>) -> EntitlementResponse {
        EntitlementResponse {
            id,
            sku_id,
            application_id,
            user_id,
            guild_id: None,
            deleted,
            starts_at: None,
            ends_at: None,
            r#type,
            fulfilled_at: None,
            fulfillment_status: None,
            consumed: None,
            gifter_user_id: None,
        }
    }
}

