/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorResponse : Errors object returned by the Discord API
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorResponse {
    /// Discord internal error code. See error code reference
    #[serde(rename = "code")]
    pub code: i32,
    /// Human-readable error message
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Box<models::ErrorDetails>>,
}

impl ErrorResponse {
    /// Errors object returned by the Discord API
    pub fn new(code: i32, message: String) -> ErrorResponse {
        ErrorResponse {
            code,
            message,
            errors: None,
        }
    }
}

