/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExecuteWebhookRequest {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(rename = "embeds", skip_serializing_if = "Option::is_none")]
    pub embeds: Option<Vec<models::RichEmbed>>,
    #[serde(rename = "allowed_mentions", skip_serializing_if = "Option::is_none")]
    pub allowed_mentions: Option<Box<models::MessageAllowedMentionsRequest>>,
    #[serde(rename = "components", skip_serializing_if = "Option::is_none")]
    pub components: Option<Vec<models::BaseCreateMessageCreateRequestComponentsInner>>,
    #[serde(rename = "attachments", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<models::MessageAttachmentRequest>>,
    #[serde(rename = "poll", skip_serializing_if = "Option::is_none")]
    pub poll: Option<Box<models::PollCreateRequest>>,
    #[serde(rename = "tts", skip_serializing_if = "Option::is_none")]
    pub tts: Option<bool>,
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<i32>,
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "avatar_url", skip_serializing_if = "Option::is_none")]
    pub avatar_url: Option<String>,
    #[serde(rename = "thread_name", skip_serializing_if = "Option::is_none")]
    pub thread_name: Option<String>,
    #[serde(rename = "applied_tags", skip_serializing_if = "Option::is_none")]
    pub applied_tags: Option<Vec<String>>,
}

impl ExecuteWebhookRequest {
    pub fn new() -> ExecuteWebhookRequest {
        ExecuteWebhookRequest {
            content: None,
            embeds: None,
            allowed_mentions: None,
            components: None,
            attachments: None,
            poll: None,
            tts: None,
            flags: None,
            username: None,
            avatar_url: None,
            thread_name: None,
            applied_tags: None,
        }
    }
}

