/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalScheduledEventCreateRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "image", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image: Option<Option<String>>,
    #[serde(rename = "scheduled_start_time")]
    pub scheduled_start_time: String,
    #[serde(rename = "scheduled_end_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scheduled_end_time: Option<Option<String>>,
    #[serde(rename = "privacy_level", deserialize_with = "Option::deserialize")]
    pub privacy_level: Option<serde_json::Value>,
    #[serde(rename = "entity_type", deserialize_with = "Option::deserialize")]
    pub entity_type: Option<i32>,
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "entity_metadata")]
    pub entity_metadata: Box<models::EntityMetadataExternal>,
}

impl ExternalScheduledEventCreateRequest {
    pub fn new(name: String, scheduled_start_time: String, privacy_level: Option<serde_json::Value>, entity_type: Option<i32>, entity_metadata: models::EntityMetadataExternal) -> ExternalScheduledEventCreateRequest {
        ExternalScheduledEventCreateRequest {
            name,
            description: None,
            image: None,
            scheduled_start_time,
            scheduled_end_time: None,
            privacy_level,
            entity_type,
            channel_id: None,
            entity_metadata: Box::new(entity_metadata),
        }
    }
}

