/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalConnectionIntegrationResponse {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<String>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "account")]
    pub account: Box<models::AccountResponse>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "user")]
    pub user: Box<models::UserResponse>,
    #[serde(rename = "revoked", skip_serializing_if = "Option::is_none")]
    pub revoked: Option<bool>,
    #[serde(rename = "expire_behavior", skip_serializing_if = "Option::is_none")]
    pub expire_behavior: Option<i32>,
    #[serde(rename = "expire_grace_period", skip_serializing_if = "Option::is_none")]
    pub expire_grace_period: Option<i32>,
    #[serde(rename = "subscriber_count", skip_serializing_if = "Option::is_none")]
    pub subscriber_count: Option<i32>,
    #[serde(rename = "synced_at", skip_serializing_if = "Option::is_none")]
    pub synced_at: Option<String>,
    #[serde(rename = "role_id", skip_serializing_if = "Option::is_none")]
    pub role_id: Option<String>,
    #[serde(rename = "syncing", skip_serializing_if = "Option::is_none")]
    pub syncing: Option<bool>,
    #[serde(rename = "enable_emoticons", skip_serializing_if = "Option::is_none")]
    pub enable_emoticons: Option<bool>,
}

impl ExternalConnectionIntegrationResponse {
    pub fn new(r#type: Option<String>, account: models::AccountResponse, enabled: bool, id: String, user: models::UserResponse) -> ExternalConnectionIntegrationResponse {
        ExternalConnectionIntegrationResponse {
            r#type,
            name: None,
            account: Box::new(account),
            enabled,
            id,
            user: Box::new(user),
            revoked: None,
            expire_behavior: None,
            expire_grace_period: None,
            subscriber_count: None,
            synced_at: None,
            role_id: None,
            syncing: None,
            enable_emoticons: None,
        }
    }
}

