/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileComponentResponse {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "file")]
    pub file: Box<models::UnfurledMediaResponse>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub size: Option<Option<i32>>,
    #[serde(rename = "spoiler")]
    pub spoiler: bool,
}

impl FileComponentResponse {
    pub fn new(r#type: i32, id: i32, file: models::UnfurledMediaResponse, spoiler: bool) -> FileComponentResponse {
        FileComponentResponse {
            r#type,
            id,
            file: Box::new(file),
            name: None,
            size: None,
            spoiler,
        }
    }
}

