/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FollowChannelRequest {
    #[serde(rename = "webhook_channel_id")]
    pub webhook_channel_id: String,
}

impl FollowChannelRequest {
    pub fn new(webhook_channel_id: String) -> FollowChannelRequest {
        FollowChannelRequest {
            webhook_channel_id,
        }
    }
}

