/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FriendInviteResponse {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<i32>,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "inviter", skip_serializing_if = "Option::is_none")]
    pub inviter: Option<Box<models::UserResponse>>,
    #[serde(rename = "max_age", skip_serializing_if = "Option::is_none")]
    pub max_age: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "expires_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<String>>,
    #[serde(rename = "friends_count", skip_serializing_if = "Option::is_none")]
    pub friends_count: Option<i32>,
    #[serde(rename = "channel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channel: Option<Option<Box<models::InviteChannelResponse>>>,
    #[serde(rename = "is_contact", skip_serializing_if = "Option::is_none")]
    pub is_contact: Option<bool>,
    #[serde(rename = "uses", skip_serializing_if = "Option::is_none")]
    pub uses: Option<i32>,
    #[serde(rename = "max_uses", skip_serializing_if = "Option::is_none")]
    pub max_uses: Option<i32>,
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<i32>,
}

impl FriendInviteResponse {
    pub fn new(r#type: Option<i32>, code: String) -> FriendInviteResponse {
        FriendInviteResponse {
            r#type,
            code,
            inviter: None,
            max_age: None,
            created_at: None,
            expires_at: None,
            friends_count: None,
            channel: None,
            is_contact: None,
            uses: None,
            max_uses: None,
            flags: None,
        }
    }
}

