/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayBotSessionStartLimitResponse {
    #[serde(rename = "max_concurrency")]
    pub max_concurrency: i32,
    #[serde(rename = "remaining")]
    pub remaining: i32,
    #[serde(rename = "reset_after")]
    pub reset_after: i32,
    #[serde(rename = "total")]
    pub total: i32,
}

impl GatewayBotSessionStartLimitResponse {
    pub fn new(max_concurrency: i32, remaining: i32, reset_after: i32, total: i32) -> GatewayBotSessionStartLimitResponse {
        GatewayBotSessionStartLimitResponse {
            max_concurrency,
            remaining,
            reset_after,
            total,
        }
    }
}

