/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GatewayBotResponse {
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "session_start_limit")]
    pub session_start_limit: Box<models::GatewayBotSessionStartLimitResponse>,
    #[serde(rename = "shards")]
    pub shards: i32,
}

impl GatewayBotResponse {
    pub fn new(url: String, session_start_limit: models::GatewayBotSessionStartLimitResponse, shards: i32) -> GatewayBotResponse {
        GatewayBotResponse {
            url,
            session_start_limit: Box::new(session_start_limit),
            shards,
        }
    }
}

