/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetSticker200Response {
    GuildStickerResponse(Box<models::GuildStickerResponse>),
    StandardStickerResponse(Box<models::StandardStickerResponse>),
}

impl Default for GetSticker200Response {
    fn default() -> Self {
        Self::GuildStickerResponse(Default::default())
    }
}

