/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubReview {
    #[serde(rename = "user")]
    pub user: Box<models::GithubUser>,
    #[serde(rename = "body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body: Option<Option<String>>,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "state")]
    pub state: String,
}

impl GithubReview {
    pub fn new(user: models::GithubUser, html_url: String, state: String) -> GithubReview {
        GithubReview {
            user: Box::new(user),
            body: None,
            html_url,
            state,
        }
    }
}

