/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubUser {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "login")]
    pub login: String,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
}

impl GithubUser {
    pub fn new(id: i32, login: String, html_url: String, avatar_url: String) -> GithubUser {
        GithubUser {
            id,
            login,
            html_url,
            avatar_url,
        }
    }
}

