/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubIssue {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "user")]
    pub user: Box<models::GithubUser>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body: Option<Option<String>>,
    #[serde(rename = "pull_request", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pull_request: Option<Option<serde_json::Value>>,
}

impl GithubIssue {
    pub fn new(id: i32, number: i32, html_url: String, user: models::GithubUser, title: String) -> GithubIssue {
        GithubIssue {
            id,
            number,
            html_url,
            user: Box::new(user),
            title,
            body: None,
            pull_request: None,
        }
    }
}

