/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubDiscussion {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "number")]
    pub number: i32,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "answer_html_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub answer_html_url: Option<Option<String>>,
    #[serde(rename = "body", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub body: Option<Option<String>>,
    #[serde(rename = "user")]
    pub user: Box<models::GithubUser>,
}

impl GithubDiscussion {
    pub fn new(title: String, number: i32, html_url: String, user: models::GithubUser) -> GithubDiscussion {
        GithubDiscussion {
            title,
            number,
            html_url,
            answer_html_url: None,
            body: None,
            user: Box::new(user),
        }
    }
}

