/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubCheckRun {
    #[serde(rename = "conclusion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub conclusion: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "check_suite")]
    pub check_suite: Box<models::GithubCheckSuite>,
    #[serde(rename = "details_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub details_url: Option<Option<String>>,
    #[serde(rename = "output", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub output: Option<Option<Box<models::GithubCheckRunOutput>>>,
    #[serde(rename = "pull_requests", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pull_requests: Option<Option<Vec<models::GithubCheckPullRequest>>>,
}

impl GithubCheckRun {
    pub fn new(name: String, html_url: String, check_suite: models::GithubCheckSuite) -> GithubCheckRun {
        GithubCheckRun {
            conclusion: None,
            name,
            html_url,
            check_suite: Box::new(check_suite),
            details_url: None,
            output: None,
            pull_requests: None,
        }
    }
}

