/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubRepository {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "full_name")]
    pub full_name: String,
}

impl GithubRepository {
    pub fn new(id: i32, html_url: String, name: String, full_name: String) -> GithubRepository {
        GithubRepository {
            id,
            html_url,
            name,
            full_name,
        }
    }
}

