/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubComment {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "user")]
    pub user: Box<models::GithubUser>,
    #[serde(rename = "commit_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commit_id: Option<Option<String>>,
    #[serde(rename = "body")]
    pub body: String,
}

impl GithubComment {
    pub fn new(id: i32, html_url: String, user: models::GithubUser, body: String) -> GithubComment {
        GithubComment {
            id,
            html_url,
            user: Box::new(user),
            commit_id: None,
            body,
        }
    }
}

