/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubWebhook {
    #[serde(rename = "action", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub action: Option<Option<String>>,
    #[serde(rename = "ref", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#ref: Option<Option<String>>,
    #[serde(rename = "ref_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ref_type: Option<Option<String>>,
    #[serde(rename = "comment", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub comment: Option<Option<Box<models::GithubComment>>>,
    #[serde(rename = "issue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub issue: Option<Option<Box<models::GithubIssue>>>,
    #[serde(rename = "pull_request", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pull_request: Option<Option<Box<models::GithubIssue>>>,
    #[serde(rename = "repository", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub repository: Option<Option<Box<models::GithubRepository>>>,
    #[serde(rename = "forkee", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub forkee: Option<Option<Box<models::GithubRepository>>>,
    #[serde(rename = "sender")]
    pub sender: Box<models::GithubUser>,
    #[serde(rename = "member", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub member: Option<Option<Box<models::GithubUser>>>,
    #[serde(rename = "release", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub release: Option<Option<Box<models::GithubRelease>>>,
    #[serde(rename = "head_commit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub head_commit: Option<Option<Box<models::GithubCommit>>>,
    #[serde(rename = "commits", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub commits: Option<Option<Vec<models::GithubCommit>>>,
    #[serde(rename = "forced", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub forced: Option<Option<bool>>,
    #[serde(rename = "compare", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compare: Option<Option<String>>,
    #[serde(rename = "review", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub review: Option<Option<Box<models::GithubReview>>>,
    #[serde(rename = "check_run", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub check_run: Option<Option<Box<models::GithubCheckRun>>>,
    #[serde(rename = "check_suite", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub check_suite: Option<Option<Box<models::GithubCheckSuite>>>,
    #[serde(rename = "discussion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub discussion: Option<Option<Box<models::GithubDiscussion>>>,
    #[serde(rename = "answer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub answer: Option<Option<Box<models::GithubComment>>>,
}

impl GithubWebhook {
    pub fn new(sender: models::GithubUser) -> GithubWebhook {
        GithubWebhook {
            action: None,
            r#ref: None,
            ref_type: None,
            comment: None,
            issue: None,
            pull_request: None,
            repository: None,
            forkee: None,
            sender: Box::new(sender),
            member: None,
            release: None,
            head_commit: None,
            commits: None,
            forced: None,
            compare: None,
            review: None,
            check_run: None,
            check_suite: None,
            discussion: None,
            answer: None,
        }
    }
}

