/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubCheckPullRequest {
    #[serde(rename = "number")]
    pub number: i32,
}

impl GithubCheckPullRequest {
    pub fn new(number: i32) -> GithubCheckPullRequest {
        GithubCheckPullRequest {
            number,
        }
    }
}

