/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubCheckSuite {
    #[serde(rename = "conclusion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub conclusion: Option<Option<String>>,
    #[serde(rename = "head_branch", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub head_branch: Option<Option<String>>,
    #[serde(rename = "head_sha")]
    pub head_sha: String,
    #[serde(rename = "pull_requests", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pull_requests: Option<Option<Vec<models::GithubCheckPullRequest>>>,
    #[serde(rename = "app")]
    pub app: Box<models::GithubCheckApp>,
}

impl GithubCheckSuite {
    pub fn new(head_sha: String, app: models::GithubCheckApp) -> GithubCheckSuite {
        GithubCheckSuite {
            conclusion: None,
            head_branch: None,
            head_sha,
            pull_requests: None,
            app: Box::new(app),
        }
    }
}

