/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GithubRelease {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "tag_name")]
    pub tag_name: String,
    #[serde(rename = "html_url")]
    pub html_url: String,
    #[serde(rename = "author")]
    pub author: Box<models::GithubUser>,
}

impl GithubRelease {
    pub fn new(id: i32, tag_name: String, html_url: String, author: models::GithubUser) -> GithubRelease {
        GithubRelease {
            id,
            tag_name,
            html_url,
            author: Box::new(author),
        }
    }
}

