/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GroupDmInviteResponse {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<i32>,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "inviter", skip_serializing_if = "Option::is_none")]
    pub inviter: Option<Box<models::UserResponse>>,
    #[serde(rename = "max_age", skip_serializing_if = "Option::is_none")]
    pub max_age: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "expires_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<String>>,
    #[serde(rename = "channel")]
    pub channel: Box<models::InviteChannelResponse>,
    #[serde(rename = "approximate_member_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub approximate_member_count: Option<Option<i32>>,
}

impl GroupDmInviteResponse {
    pub fn new(r#type: Option<i32>, code: String, channel: models::InviteChannelResponse) -> GroupDmInviteResponse {
        GroupDmInviteResponse {
            r#type,
            code,
            inviter: None,
            max_age: None,
            created_at: None,
            expires_at: None,
            channel: Box::new(channel),
            approximate_member_count: None,
        }
    }
}

