/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildProductPurchaseResponse {
    #[serde(rename = "listing_id")]
    pub listing_id: String,
    #[serde(rename = "product_name")]
    pub product_name: String,
}

impl GuildProductPurchaseResponse {
    pub fn new(listing_id: String, product_name: String) -> GuildProductPurchaseResponse {
        GuildProductPurchaseResponse {
            listing_id,
            product_name,
        }
    }
}

