/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildBanResponse {
    #[serde(rename = "user")]
    pub user: Box<models::UserResponse>,
    #[serde(rename = "reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reason: Option<Option<String>>,
}

impl GuildBanResponse {
    pub fn new(user: models::UserResponse) -> GuildBanResponse {
        GuildBanResponse {
            user: Box::new(user),
            reason: None,
        }
    }
}

