/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildHomeSettingsResponse {
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "welcome_message", skip_serializing_if = "Option::is_none")]
    pub welcome_message: Option<Box<models::WelcomeMessageResponse>>,
    #[serde(rename = "new_member_actions")]
    pub new_member_actions: Vec<models::NewMemberActionResponse>,
    #[serde(rename = "resource_channels")]
    pub resource_channels: Vec<models::ResourceChannelResponse>,
}

impl GuildHomeSettingsResponse {
    pub fn new(guild_id: String, enabled: bool, new_member_actions: Vec<models::NewMemberActionResponse>, resource_channels: Vec<models::ResourceChannelResponse>) -> GuildHomeSettingsResponse {
        GuildHomeSettingsResponse {
            guild_id,
            enabled,
            welcome_message: None,
            new_member_actions,
            resource_channels,
        }
    }
}

