/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildWelcomeScreenResponse {
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "welcome_channels")]
    pub welcome_channels: Vec<models::GuildWelcomeScreenChannelResponse>,
}

impl GuildWelcomeScreenResponse {
    pub fn new(welcome_channels: Vec<models::GuildWelcomeScreenChannelResponse>) -> GuildWelcomeScreenResponse {
        GuildWelcomeScreenResponse {
            description: None,
            welcome_channels,
        }
    }
}

