/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildRoleTagsResponse {
    #[serde(rename = "premium_subscriber", skip_serializing_if = "Option::is_none")]
    pub premium_subscriber: Option<models::Null>,
    #[serde(rename = "bot_id", skip_serializing_if = "Option::is_none")]
    pub bot_id: Option<String>,
    #[serde(rename = "integration_id", skip_serializing_if = "Option::is_none")]
    pub integration_id: Option<String>,
    #[serde(rename = "subscription_listing_id", skip_serializing_if = "Option::is_none")]
    pub subscription_listing_id: Option<String>,
    #[serde(rename = "available_for_purchase", skip_serializing_if = "Option::is_none")]
    pub available_for_purchase: Option<models::Null>,
    #[serde(rename = "guild_connections", skip_serializing_if = "Option::is_none")]
    pub guild_connections: Option<models::Null>,
}

impl GuildRoleTagsResponse {
    pub fn new() -> GuildRoleTagsResponse {
        GuildRoleTagsResponse {
            premium_subscriber: None,
            bot_id: None,
            integration_id: None,
            subscription_listing_id: None,
            available_for_purchase: None,
            guild_connections: None,
        }
    }
}

