/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildTemplateResponse {
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "usage_count")]
    pub usage_count: i32,
    #[serde(rename = "creator_id")]
    pub creator_id: String,
    #[serde(rename = "creator", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub creator: Option<Option<Box<models::UserResponse>>>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "updated_at")]
    pub updated_at: String,
    #[serde(rename = "source_guild_id")]
    pub source_guild_id: String,
    #[serde(rename = "serialized_source_guild")]
    pub serialized_source_guild: Box<models::GuildTemplateSnapshotResponse>,
    #[serde(rename = "is_dirty", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_dirty: Option<Option<bool>>,
}

impl GuildTemplateResponse {
    pub fn new(code: String, name: String, usage_count: i32, creator_id: String, created_at: String, updated_at: String, source_guild_id: String, serialized_source_guild: models::GuildTemplateSnapshotResponse) -> GuildTemplateResponse {
        GuildTemplateResponse {
            code,
            name,
            description: None,
            usage_count,
            creator_id,
            creator: None,
            created_at,
            updated_at,
            source_guild_id,
            serialized_source_guild: Box::new(serialized_source_guild),
            is_dirty: None,
        }
    }
}

