/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildPatchRequestPartial {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub region: Option<Option<String>>,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "verification_level", skip_serializing_if = "Option::is_none")]
    pub verification_level: Option<i32>,
    #[serde(rename = "default_message_notifications", skip_serializing_if = "Option::is_none")]
    pub default_message_notifications: Option<i32>,
    #[serde(rename = "explicit_content_filter", skip_serializing_if = "Option::is_none")]
    pub explicit_content_filter: Option<i32>,
    #[serde(rename = "preferred_locale", skip_serializing_if = "Option::is_none")]
    pub preferred_locale: Option<String>,
    #[serde(rename = "afk_timeout", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub afk_timeout: Option<Option<i32>>,
    #[serde(rename = "afk_channel_id", skip_serializing_if = "Option::is_none")]
    pub afk_channel_id: Option<String>,
    #[serde(rename = "system_channel_id", skip_serializing_if = "Option::is_none")]
    pub system_channel_id: Option<String>,
    #[serde(rename = "splash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub splash: Option<Option<String>>,
    #[serde(rename = "banner", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub banner: Option<Option<String>>,
    #[serde(rename = "system_channel_flags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub system_channel_flags: Option<Option<i32>>,
    #[serde(rename = "features", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub features: Option<Option<Vec<String>>>,
    #[serde(rename = "discovery_splash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub discovery_splash: Option<Option<String>>,
    #[serde(rename = "home_header", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub home_header: Option<Option<String>>,
    #[serde(rename = "rules_channel_id", skip_serializing_if = "Option::is_none")]
    pub rules_channel_id: Option<String>,
    #[serde(rename = "safety_alerts_channel_id", skip_serializing_if = "Option::is_none")]
    pub safety_alerts_channel_id: Option<String>,
    #[serde(rename = "public_updates_channel_id", skip_serializing_if = "Option::is_none")]
    pub public_updates_channel_id: Option<String>,
    #[serde(rename = "premium_progress_bar_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub premium_progress_bar_enabled: Option<Option<bool>>,
}

impl GuildPatchRequestPartial {
    pub fn new() -> GuildPatchRequestPartial {
        GuildPatchRequestPartial {
            name: None,
            description: None,
            region: None,
            icon: None,
            verification_level: None,
            default_message_notifications: None,
            explicit_content_filter: None,
            preferred_locale: None,
            afk_timeout: None,
            afk_channel_id: None,
            system_channel_id: None,
            splash: None,
            banner: None,
            system_channel_flags: None,
            features: None,
            discovery_splash: None,
            home_header: None,
            rules_channel_id: None,
            safety_alerts_channel_id: None,
            public_updates_channel_id: None,
            premium_progress_bar_enabled: None,
        }
    }
}

