/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildOnboardingResponse {
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "prompts")]
    pub prompts: Vec<models::OnboardingPromptResponse>,
    #[serde(rename = "default_channel_ids")]
    pub default_channel_ids: Vec<String>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
}

impl GuildOnboardingResponse {
    pub fn new(guild_id: String, prompts: Vec<models::OnboardingPromptResponse>, default_channel_ids: Vec<String>, enabled: bool) -> GuildOnboardingResponse {
        GuildOnboardingResponse {
            guild_id,
            prompts,
            default_channel_ids,
            enabled,
        }
    }
}

