/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildSubscriptionIntegrationResponse {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<String>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "account")]
    pub account: Box<models::AccountResponse>,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "id")]
    pub id: String,
}

impl GuildSubscriptionIntegrationResponse {
    pub fn new(r#type: Option<String>, account: models::AccountResponse, enabled: bool, id: String) -> GuildSubscriptionIntegrationResponse {
        GuildSubscriptionIntegrationResponse {
            r#type,
            name: None,
            account: Box::new(account),
            enabled,
            id,
        }
    }
}

