/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildRoleResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "permissions")]
    pub permissions: String,
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "color")]
    pub color: i32,
    #[serde(rename = "colors")]
    pub colors: Box<models::GuildRoleColorsResponse>,
    #[serde(rename = "hoist")]
    pub hoist: bool,
    #[serde(rename = "managed")]
    pub managed: bool,
    #[serde(rename = "mentionable")]
    pub mentionable: bool,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "unicode_emoji", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unicode_emoji: Option<Option<String>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Box<models::GuildRoleTagsResponse>>,
    #[serde(rename = "flags")]
    pub flags: i32,
}

impl GuildRoleResponse {
    pub fn new(id: String, name: String, permissions: String, position: i32, color: i32, colors: models::GuildRoleColorsResponse, hoist: bool, managed: bool, mentionable: bool, flags: i32) -> GuildRoleResponse {
        GuildRoleResponse {
            id,
            name,
            description: None,
            permissions,
            position,
            color,
            colors: Box::new(colors),
            hoist,
            managed,
            mentionable,
            icon: None,
            unicode_emoji: None,
            tags: None,
            flags,
        }
    }
}

