/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildPreviewResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "home_header", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub home_header: Option<Option<String>>,
    #[serde(rename = "splash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub splash: Option<Option<String>>,
    #[serde(rename = "discovery_splash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub discovery_splash: Option<Option<String>>,
    #[serde(rename = "features")]
    pub features: Vec<String>,
    #[serde(rename = "approximate_member_count")]
    pub approximate_member_count: i32,
    #[serde(rename = "approximate_presence_count")]
    pub approximate_presence_count: i32,
    #[serde(rename = "emojis")]
    pub emojis: Vec<models::EmojiResponse>,
    #[serde(rename = "stickers")]
    pub stickers: Vec<models::GuildStickerResponse>,
}

impl GuildPreviewResponse {
    pub fn new(id: String, name: String, features: Vec<String>, approximate_member_count: i32, approximate_presence_count: i32, emojis: Vec<models::EmojiResponse>, stickers: Vec<models::GuildStickerResponse>) -> GuildPreviewResponse {
        GuildPreviewResponse {
            id,
            name,
            icon: None,
            description: None,
            home_header: None,
            splash: None,
            discovery_splash: None,
            features,
            approximate_member_count,
            approximate_presence_count,
            emojis,
            stickers,
        }
    }
}

