/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildTemplateRoleColorsResponse {
    #[serde(rename = "primary_color")]
    pub primary_color: i32,
    #[serde(rename = "secondary_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secondary_color: Option<Option<i32>>,
    #[serde(rename = "tertiary_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tertiary_color: Option<Option<i32>>,
}

impl GuildTemplateRoleColorsResponse {
    pub fn new(primary_color: i32) -> GuildTemplateRoleColorsResponse {
        GuildTemplateRoleColorsResponse {
            primary_color,
            secondary_color: None,
            tertiary_color: None,
        }
    }
}

