/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildTemplateSnapshotResponse {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub region: Option<Option<String>>,
    #[serde(rename = "verification_level")]
    pub verification_level: i32,
    #[serde(rename = "default_message_notifications")]
    pub default_message_notifications: i32,
    #[serde(rename = "explicit_content_filter")]
    pub explicit_content_filter: i32,
    #[serde(rename = "preferred_locale")]
    pub preferred_locale: String,
    #[serde(rename = "afk_channel_id", skip_serializing_if = "Option::is_none")]
    pub afk_channel_id: Option<String>,
    #[serde(rename = "afk_timeout", deserialize_with = "Option::deserialize")]
    pub afk_timeout: Option<i32>,
    #[serde(rename = "system_channel_id", skip_serializing_if = "Option::is_none")]
    pub system_channel_id: Option<String>,
    #[serde(rename = "system_channel_flags")]
    pub system_channel_flags: i32,
    #[serde(rename = "roles")]
    pub roles: Vec<models::GuildTemplateRoleResponse>,
    #[serde(rename = "channels")]
    pub channels: Vec<models::GuildTemplateChannelResponse>,
}

impl GuildTemplateSnapshotResponse {
    pub fn new(name: String, verification_level: i32, default_message_notifications: i32, explicit_content_filter: i32, preferred_locale: String, afk_timeout: Option<i32>, system_channel_flags: i32, roles: Vec<models::GuildTemplateRoleResponse>, channels: Vec<models::GuildTemplateChannelResponse>) -> GuildTemplateSnapshotResponse {
        GuildTemplateSnapshotResponse {
            name,
            description: None,
            region: None,
            verification_level,
            default_message_notifications,
            explicit_content_filter,
            preferred_locale,
            afk_channel_id: None,
            afk_timeout,
            system_channel_id: None,
            system_channel_flags,
            roles,
            channels,
        }
    }
}

