/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildInviteResponse {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<i32>,
    #[serde(rename = "code")]
    pub code: String,
    #[serde(rename = "inviter", skip_serializing_if = "Option::is_none")]
    pub inviter: Option<Box<models::UserResponse>>,
    #[serde(rename = "max_age", skip_serializing_if = "Option::is_none")]
    pub max_age: Option<i32>,
    #[serde(rename = "created_at", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "expires_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at: Option<Option<String>>,
    #[serde(rename = "is_contact", skip_serializing_if = "Option::is_none")]
    pub is_contact: Option<bool>,
    #[serde(rename = "flags", skip_serializing_if = "Option::is_none")]
    pub flags: Option<i32>,
    #[serde(rename = "guild")]
    pub guild: Box<models::InviteGuildResponse>,
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "channel")]
    pub channel: Box<models::InviteChannelResponse>,
    #[serde(rename = "target_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub target_type: Option<Option<i32>>,
    #[serde(rename = "target_user", skip_serializing_if = "Option::is_none")]
    pub target_user: Option<Box<models::UserResponse>>,
    #[serde(rename = "target_application", skip_serializing_if = "Option::is_none")]
    pub target_application: Option<Box<models::InviteApplicationResponse>>,
    #[serde(rename = "guild_scheduled_event", skip_serializing_if = "Option::is_none")]
    pub guild_scheduled_event: Option<Box<models::ScheduledEventResponse>>,
    #[serde(rename = "uses", skip_serializing_if = "Option::is_none")]
    pub uses: Option<i32>,
    #[serde(rename = "max_uses", skip_serializing_if = "Option::is_none")]
    pub max_uses: Option<i32>,
    #[serde(rename = "temporary", skip_serializing_if = "Option::is_none")]
    pub temporary: Option<bool>,
    #[serde(rename = "approximate_member_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub approximate_member_count: Option<Option<i32>>,
    #[serde(rename = "approximate_presence_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub approximate_presence_count: Option<Option<i32>>,
    #[serde(rename = "is_nickname_changeable", skip_serializing_if = "Option::is_none")]
    pub is_nickname_changeable: Option<bool>,
}

impl GuildInviteResponse {
    pub fn new(r#type: Option<i32>, code: String, guild: models::InviteGuildResponse, guild_id: String, channel: models::InviteChannelResponse) -> GuildInviteResponse {
        GuildInviteResponse {
            r#type,
            code,
            inviter: None,
            max_age: None,
            created_at: None,
            expires_at: None,
            is_contact: None,
            flags: None,
            guild: Box::new(guild),
            guild_id,
            channel: Box::new(channel),
            target_type: None,
            target_user: None,
            target_application: None,
            guild_scheduled_event: None,
            uses: None,
            max_uses: None,
            temporary: None,
            approximate_member_count: None,
            approximate_presence_count: None,
            is_nickname_changeable: None,
        }
    }
}

