/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildStickerResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tags")]
    pub tags: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "format_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub format_type: Option<Option<i32>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "available")]
    pub available: bool,
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserResponse>>,
}

impl GuildStickerResponse {
    pub fn new(id: String, name: String, tags: String, r#type: i32, available: bool, guild_id: String) -> GuildStickerResponse {
        GuildStickerResponse {
            id,
            name,
            tags,
            r#type,
            format_type: None,
            description: None,
            available,
            guild_id,
            user: None,
        }
    }
}

