/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildChannelResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "last_message_id", skip_serializing_if = "Option::is_none")]
    pub last_message_id: Option<String>,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "last_pin_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_pin_timestamp: Option<Option<String>>,
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "parent_id", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "rate_limit_per_user", skip_serializing_if = "Option::is_none")]
    pub rate_limit_per_user: Option<i32>,
    #[serde(rename = "bitrate", skip_serializing_if = "Option::is_none")]
    pub bitrate: Option<i32>,
    #[serde(rename = "user_limit", skip_serializing_if = "Option::is_none")]
    pub user_limit: Option<i32>,
    #[serde(rename = "rtc_region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rtc_region: Option<Option<String>>,
    #[serde(rename = "video_quality_mode", skip_serializing_if = "Option::is_none")]
    pub video_quality_mode: Option<i32>,
    #[serde(rename = "permissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Option<String>>,
    #[serde(rename = "topic", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub topic: Option<Option<String>>,
    #[serde(rename = "default_auto_archive_duration", skip_serializing_if = "Option::is_none")]
    pub default_auto_archive_duration: Option<i32>,
    #[serde(rename = "default_thread_rate_limit_per_user", skip_serializing_if = "Option::is_none")]
    pub default_thread_rate_limit_per_user: Option<i32>,
    #[serde(rename = "position")]
    pub position: i32,
    #[serde(rename = "permission_overwrites", skip_serializing_if = "Option::is_none")]
    pub permission_overwrites: Option<Vec<models::ChannelPermissionOverwriteResponse>>,
    #[serde(rename = "nsfw", skip_serializing_if = "Option::is_none")]
    pub nsfw: Option<bool>,
    #[serde(rename = "available_tags", skip_serializing_if = "Option::is_none")]
    pub available_tags: Option<Vec<models::ForumTagResponse>>,
    #[serde(rename = "default_reaction_emoji", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_reaction_emoji: Option<Option<Box<models::DefaultReactionEmojiResponse>>>,
    #[serde(rename = "default_sort_order", skip_serializing_if = "Option::is_none")]
    pub default_sort_order: Option<i32>,
    #[serde(rename = "default_forum_layout", skip_serializing_if = "Option::is_none")]
    pub default_forum_layout: Option<i32>,
    #[serde(rename = "default_tag_setting", skip_serializing_if = "Option::is_none")]
    pub default_tag_setting: Option<String>,
    #[serde(rename = "hd_streaming_until", skip_serializing_if = "Option::is_none")]
    pub hd_streaming_until: Option<String>,
    #[serde(rename = "hd_streaming_buyer_id", skip_serializing_if = "Option::is_none")]
    pub hd_streaming_buyer_id: Option<String>,
}

impl GuildChannelResponse {
    pub fn new(id: String, r#type: i32, flags: i32, guild_id: String, name: String, position: i32) -> GuildChannelResponse {
        GuildChannelResponse {
            id,
            r#type,
            last_message_id: None,
            flags,
            last_pin_timestamp: None,
            guild_id,
            name,
            parent_id: None,
            rate_limit_per_user: None,
            bitrate: None,
            user_limit: None,
            rtc_region: None,
            video_quality_mode: None,
            permissions: None,
            topic: None,
            default_auto_archive_duration: None,
            default_thread_rate_limit_per_user: None,
            position,
            permission_overwrites: None,
            nsfw: None,
            available_tags: None,
            default_reaction_emoji: None,
            default_sort_order: None,
            default_forum_layout: None,
            default_tag_setting: None,
            hd_streaming_until: None,
            hd_streaming_buyer_id: None,
        }
    }
}

