/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GuildTemplateRoleResponse {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "permissions")]
    pub permissions: String,
    #[serde(rename = "color")]
    pub color: i32,
    #[serde(rename = "colors", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub colors: Option<Option<Box<models::GuildTemplateRoleColorsResponse>>>,
    #[serde(rename = "hoist")]
    pub hoist: bool,
    #[serde(rename = "mentionable")]
    pub mentionable: bool,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "unicode_emoji", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unicode_emoji: Option<Option<String>>,
}

impl GuildTemplateRoleResponse {
    pub fn new(id: i32, name: String, permissions: String, color: i32, hoist: bool, mentionable: bool) -> GuildTemplateRoleResponse {
        GuildTemplateRoleResponse {
            id,
            name,
            permissions,
            color,
            colors: None,
            hoist,
            mentionable,
            icon: None,
            unicode_emoji: None,
        }
    }
}

