/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InnerErrors {
    /// The list of errors for this field
    #[serde(rename = "_errors")]
    pub _errors: Vec<models::Error>,
}

impl InnerErrors {
    pub fn new(_errors: Vec<models::Error>) -> InnerErrors {
        InnerErrors {
            _errors,
        }
    }
}

