/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntegrationApplicationResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<i32>>,
    #[serde(rename = "cover_image", skip_serializing_if = "Option::is_none")]
    pub cover_image: Option<String>,
    #[serde(rename = "primary_sku_id", skip_serializing_if = "Option::is_none")]
    pub primary_sku_id: Option<String>,
    #[serde(rename = "bot", skip_serializing_if = "Option::is_none")]
    pub bot: Option<Box<models::UserResponse>>,
}

impl IntegrationApplicationResponse {
    pub fn new(id: String, name: String, description: String) -> IntegrationApplicationResponse {
        IntegrationApplicationResponse {
            id,
            name,
            icon: None,
            description,
            r#type: None,
            cover_image: None,
            primary_sku_id: None,
            bot: None,
        }
    }
}

