/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InteractionResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "response_message_id", skip_serializing_if = "Option::is_none")]
    pub response_message_id: Option<String>,
    #[serde(rename = "response_message_loading", skip_serializing_if = "Option::is_none")]
    pub response_message_loading: Option<bool>,
    #[serde(rename = "response_message_ephemeral", skip_serializing_if = "Option::is_none")]
    pub response_message_ephemeral: Option<bool>,
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "guild_id", skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<String>,
}

impl InteractionResponse {
    pub fn new(id: String, r#type: i32) -> InteractionResponse {
        InteractionResponse {
            id,
            r#type,
            response_message_id: None,
            response_message_loading: None,
            response_message_ephemeral: None,
            channel_id: None,
            guild_id: None,
        }
    }
}

