/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum InteractionCallbackResponseResource {
    CreateMessageInteractionCallbackResponse(Box<models::CreateMessageInteractionCallbackResponse>),
    LaunchActivityInteractionCallbackResponse(Box<models::LaunchActivityInteractionCallbackResponse>),
    UpdateMessageInteractionCallbackResponse(Box<models::UpdateMessageInteractionCallbackResponse>),
}

impl Default for InteractionCallbackResponseResource {
    fn default() -> Self {
        Self::CreateMessageInteractionCallbackResponse(Default::default())
    }
}

