/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InteractionCallbackResponse {
    #[serde(rename = "interaction")]
    pub interaction: Box<models::InteractionResponse>,
    #[serde(rename = "resource", skip_serializing_if = "Option::is_none")]
    pub resource: Option<Box<models::InteractionCallbackResponseResource>>,
}

impl InteractionCallbackResponse {
    pub fn new(interaction: models::InteractionResponse) -> InteractionCallbackResponse {
        InteractionCallbackResponse {
            interaction: Box::new(interaction),
            resource: None,
        }
    }
}

