/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteChannelRecipientResponse {
    #[serde(rename = "username")]
    pub username: String,
}

impl InviteChannelRecipientResponse {
    pub fn new(username: String) -> InviteChannelRecipientResponse {
        InviteChannelRecipientResponse {
            username,
        }
    }
}

