/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InviteGuildResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "splash", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub splash: Option<Option<String>>,
    #[serde(rename = "banner", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub banner: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "features")]
    pub features: Vec<String>,
    #[serde(rename = "verification_level", skip_serializing_if = "Option::is_none")]
    pub verification_level: Option<i32>,
    #[serde(rename = "vanity_url_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub vanity_url_code: Option<Option<String>>,
    #[serde(rename = "nsfw_level", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nsfw_level: Option<Option<i32>>,
    #[serde(rename = "nsfw", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nsfw: Option<Option<bool>>,
    #[serde(rename = "premium_subscription_count")]
    pub premium_subscription_count: i32,
}

impl InviteGuildResponse {
    pub fn new(id: String, name: String, features: Vec<String>, premium_subscription_count: i32) -> InviteGuildResponse {
        InviteGuildResponse {
            id,
            name,
            splash: None,
            banner: None,
            description: None,
            icon: None,
            features,
            verification_level: None,
            vanity_url_code: None,
            nsfw_level: None,
            nsfw: None,
            premium_subscription_count,
        }
    }
}

