/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeywordTriggerMetadataResponse {
    #[serde(rename = "keyword_filter")]
    pub keyword_filter: Vec<String>,
    #[serde(rename = "regex_patterns")]
    pub regex_patterns: Vec<String>,
    #[serde(rename = "allow_list")]
    pub allow_list: Vec<String>,
}

impl KeywordTriggerMetadataResponse {
    pub fn new(keyword_filter: Vec<String>, regex_patterns: Vec<String>, allow_list: Vec<String>) -> KeywordTriggerMetadataResponse {
        KeywordTriggerMetadataResponse {
            keyword_filter,
            regex_patterns,
            allow_list,
        }
    }
}

