/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeywordTriggerMetadata {
    #[serde(rename = "keyword_filter", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub keyword_filter: Option<Option<Vec<String>>>,
    #[serde(rename = "regex_patterns", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub regex_patterns: Option<Option<Vec<String>>>,
    #[serde(rename = "allow_list", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allow_list: Option<Option<Vec<String>>>,
}

impl KeywordTriggerMetadata {
    pub fn new() -> KeywordTriggerMetadata {
        KeywordTriggerMetadata {
            keyword_filter: None,
            regex_patterns: None,
            allow_list: None,
        }
    }
}

