/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LabelComponentForModalRequest {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "component")]
    pub component: Box<models::LabelComponentForModalRequestComponent>,
}

impl LabelComponentForModalRequest {
    pub fn new(r#type: i32, label: String, component: models::LabelComponentForModalRequestComponent) -> LabelComponentForModalRequest {
        LabelComponentForModalRequest {
            r#type,
            id: None,
            label,
            description: None,
            component: Box::new(component),
        }
    }
}

