/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum LabelComponentForModalRequestComponent {
    ChannelSelectComponentForModalRequest(Box<models::ChannelSelectComponentForModalRequest>),
    FileUploadComponentForModalRequest(Box<models::FileUploadComponentForModalRequest>),
    MentionableSelectComponentForModalRequest(Box<models::MentionableSelectComponentForModalRequest>),
    RoleSelectComponentForModalRequest(Box<models::RoleSelectComponentForModalRequest>),
    StringSelectComponentForModalRequest(Box<models::StringSelectComponentForModalRequest>),
    TextInputComponentForModalRequest(Box<models::TextInputComponentForModalRequest>),
    UserSelectComponentForModalRequest(Box<models::UserSelectComponentForModalRequest>),
}

impl Default for LabelComponentForModalRequestComponent {
    fn default() -> Self {
        Self::ChannelSelectComponentForModalRequest(Default::default())
    }
}

