/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ListChannelWebhooks200ResponseInner {
    ApplicationIncomingWebhookResponse(Box<models::ApplicationIncomingWebhookResponse>),
    ChannelFollowerWebhookResponse(Box<models::ChannelFollowerWebhookResponse>),
    GuildIncomingWebhookResponse(Box<models::GuildIncomingWebhookResponse>),
}

impl Default for ListChannelWebhooks200ResponseInner {
    fn default() -> Self {
        Self::ApplicationIncomingWebhookResponse(Default::default())
    }
}

