/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LobbyMessageResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "lobby_id")]
    pub lobby_id: String,
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "author")]
    pub author: Box<models::UserResponse>,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "application_id", skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
}

impl LobbyMessageResponse {
    pub fn new(id: String, r#type: i32, content: String, lobby_id: String, channel_id: String, author: models::UserResponse, flags: i32) -> LobbyMessageResponse {
        LobbyMessageResponse {
            id,
            r#type,
            content,
            lobby_id,
            channel_id,
            author: Box::new(author),
            metadata: None,
            flags,
            application_id: None,
        }
    }
}

