/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LobbyMemberResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "flags")]
    pub flags: i32,
}

impl LobbyMemberResponse {
    pub fn new(id: String, flags: i32) -> LobbyMemberResponse {
        LobbyMemberResponse {
            id,
            metadata: None,
            flags,
        }
    }
}

