/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LobbyResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "application_id")]
    pub application_id: String,
    #[serde(rename = "metadata", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<std::collections::HashMap<String, String>>,
    #[serde(rename = "members")]
    pub members: Vec<models::LobbyMemberResponse>,
    #[serde(rename = "linked_channel", skip_serializing_if = "Option::is_none")]
    pub linked_channel: Option<Box<models::GuildChannelResponse>>,
    #[serde(rename = "flags")]
    pub flags: i64,
    #[serde(rename = "override_event_webhooks_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub override_event_webhooks_url: Option<Option<String>>,
}

impl LobbyResponse {
    pub fn new(id: String, application_id: String, members: Vec<models::LobbyMemberResponse>, flags: i64) -> LobbyResponse {
        LobbyResponse {
            id,
            application_id,
            metadata: None,
            members,
            linked_channel: None,
            flags,
            override_event_webhooks_url: None,
        }
    }
}

