/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaGalleryComponentForMessageRequest {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    #[serde(rename = "items")]
    pub items: Vec<models::MediaGalleryItemRequest>,
}

impl MediaGalleryComponentForMessageRequest {
    pub fn new(r#type: i32, items: Vec<models::MediaGalleryItemRequest>) -> MediaGalleryComponentForMessageRequest {
        MediaGalleryComponentForMessageRequest {
            r#type,
            id: None,
            items,
        }
    }
}

