/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaGalleryComponentResponse {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "items")]
    pub items: Vec<models::MediaGalleryItemResponse>,
}

impl MediaGalleryComponentResponse {
    pub fn new(r#type: i32, id: i32, items: Vec<models::MediaGalleryItemResponse>) -> MediaGalleryComponentResponse {
        MediaGalleryComponentResponse {
            r#type,
            id,
            items,
        }
    }
}

