/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaGalleryItemResponse {
    #[serde(rename = "media")]
    pub media: Box<models::UnfurledMediaResponse>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "spoiler")]
    pub spoiler: bool,
}

impl MediaGalleryItemResponse {
    pub fn new(media: models::UnfurledMediaResponse, spoiler: bool) -> MediaGalleryItemResponse {
        MediaGalleryItemResponse {
            media: Box::new(media),
            description: None,
            spoiler,
        }
    }
}

