/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum MentionableSelectComponentForMessageRequestDefaultValuesInner {
    RoleSelectDefaultValue(Box<models::RoleSelectDefaultValue>),
    UserSelectDefaultValue(Box<models::UserSelectDefaultValue>),
}

impl Default for MentionableSelectComponentForMessageRequestDefaultValuesInner {
    fn default() -> Self {
        Self::RoleSelectDefaultValue(Default::default())
    }
}

