/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MentionSpamTriggerMetadataResponse {
    #[serde(rename = "mention_total_limit")]
    pub mention_total_limit: i32,
    #[serde(rename = "mention_raid_protection_enabled")]
    pub mention_raid_protection_enabled: bool,
}

impl MentionSpamTriggerMetadataResponse {
    pub fn new(mention_total_limit: i32, mention_raid_protection_enabled: bool) -> MentionSpamTriggerMetadataResponse {
        MentionSpamTriggerMetadataResponse {
            mention_total_limit,
            mention_raid_protection_enabled,
        }
    }
}

