/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MentionSpamTriggerMetadata {
    #[serde(rename = "mention_total_limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mention_total_limit: Option<Option<i32>>,
    #[serde(rename = "mention_raid_protection_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub mention_raid_protection_enabled: Option<Option<bool>>,
}

impl MentionSpamTriggerMetadata {
    pub fn new() -> MentionSpamTriggerMetadata {
        MentionSpamTriggerMetadata {
            mention_total_limit: None,
            mention_raid_protection_enabled: None,
        }
    }
}

