/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageInteractionResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserResponse>>,
    #[serde(rename = "name_localized", skip_serializing_if = "Option::is_none")]
    pub name_localized: Option<String>,
}

impl MessageInteractionResponse {
    pub fn new(id: String, r#type: i32, name: String) -> MessageInteractionResponse {
        MessageInteractionResponse {
            id,
            r#type,
            name,
            user: None,
            name_localized: None,
        }
    }
}

