/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageCallResponse {
    #[serde(rename = "ended_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ended_timestamp: Option<Option<String>>,
    #[serde(rename = "participants")]
    pub participants: Vec<String>,
}

impl MessageCallResponse {
    pub fn new(participants: Vec<String>) -> MessageCallResponse {
        MessageCallResponse {
            ended_timestamp: None,
            participants,
        }
    }
}

