/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageEmbedAuthorResponse {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    #[serde(rename = "icon_url", skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<String>,
    #[serde(rename = "proxy_icon_url", skip_serializing_if = "Option::is_none")]
    pub proxy_icon_url: Option<String>,
}

impl MessageEmbedAuthorResponse {
    pub fn new(name: String) -> MessageEmbedAuthorResponse {
        MessageEmbedAuthorResponse {
            name,
            url: None,
            icon_url: None,
            proxy_icon_url: None,
        }
    }
}

