/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageAllowedMentionsRequest {
    #[serde(rename = "parse", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parse: Option<Option<Vec<String>>>,
    #[serde(rename = "users", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub users: Option<Option<Vec<String>>>,
    #[serde(rename = "roles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub roles: Option<Option<Vec<String>>>,
    #[serde(rename = "replied_user", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub replied_user: Option<Option<bool>>,
}

impl MessageAllowedMentionsRequest {
    pub fn new() -> MessageAllowedMentionsRequest {
        MessageAllowedMentionsRequest {
            parse: None,
            users: None,
            roles: None,
            replied_user: None,
        }
    }
}

