/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageEditRequestPartial {
    #[serde(rename = "content", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content: Option<Option<String>>,
    #[serde(rename = "embeds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub embeds: Option<Option<Vec<models::RichEmbed>>>,
    #[serde(rename = "flags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Option<i32>>,
    #[serde(rename = "allowed_mentions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_mentions: Option<Option<Box<models::MessageAllowedMentionsRequest>>>,
    #[serde(rename = "sticker_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sticker_ids: Option<Option<Vec<String>>>,
    #[serde(rename = "components", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub components: Option<Option<Vec<models::BaseCreateMessageCreateRequestComponentsInner>>>,
    #[serde(rename = "attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<Vec<models::MessageAttachmentRequest>>>,
}

impl MessageEditRequestPartial {
    pub fn new() -> MessageEditRequestPartial {
        MessageEditRequestPartial {
            content: None,
            embeds: None,
            flags: None,
            allowed_mentions: None,
            sticker_ids: None,
            components: None,
            attachments: None,
        }
    }
}

