/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageStickerItemResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "format_type", deserialize_with = "Option::deserialize")]
    pub format_type: Option<i32>,
}

impl MessageStickerItemResponse {
    pub fn new(id: String, name: String, format_type: Option<i32>) -> MessageStickerItemResponse {
        MessageStickerItemResponse {
            id,
            name,
            format_type,
        }
    }
}

