/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageRoleSubscriptionDataResponse {
    #[serde(rename = "role_subscription_listing_id")]
    pub role_subscription_listing_id: String,
    #[serde(rename = "tier_name")]
    pub tier_name: String,
    #[serde(rename = "total_months_subscribed")]
    pub total_months_subscribed: i32,
    #[serde(rename = "is_renewal")]
    pub is_renewal: bool,
}

impl MessageRoleSubscriptionDataResponse {
    pub fn new(role_subscription_listing_id: String, tier_name: String, total_months_subscribed: i32, is_renewal: bool) -> MessageRoleSubscriptionDataResponse {
        MessageRoleSubscriptionDataResponse {
            role_subscription_listing_id,
            tier_name,
            total_months_subscribed,
            is_renewal,
        }
    }
}

