/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageMentionChannelResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "guild_id")]
    pub guild_id: String,
}

impl MessageMentionChannelResponse {
    pub fn new(id: String, name: String, r#type: i32, guild_id: String) -> MessageMentionChannelResponse {
        MessageMentionChannelResponse {
            id,
            name,
            r#type,
            guild_id,
        }
    }
}

