/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageAttachmentResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "size")]
    pub size: i32,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "proxy_url")]
    pub proxy_url: String,
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    #[serde(rename = "duration_secs", skip_serializing_if = "Option::is_none")]
    pub duration_secs: Option<f64>,
    #[serde(rename = "waveform", skip_serializing_if = "Option::is_none")]
    pub waveform: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "content_type", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(rename = "ephemeral", skip_serializing_if = "Option::is_none")]
    pub ephemeral: Option<bool>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "application", skip_serializing_if = "Option::is_none")]
    pub application: Option<Box<models::ApplicationResponse>>,
    #[serde(rename = "clip_created_at", skip_serializing_if = "Option::is_none")]
    pub clip_created_at: Option<String>,
    #[serde(rename = "clip_participants", skip_serializing_if = "Option::is_none")]
    pub clip_participants: Option<Vec<models::UserResponse>>,
}

impl MessageAttachmentResponse {
    pub fn new(id: String, filename: String, size: i32, url: String, proxy_url: String) -> MessageAttachmentResponse {
        MessageAttachmentResponse {
            id,
            filename,
            size,
            url,
            proxy_url,
            width: None,
            height: None,
            duration_secs: None,
            waveform: None,
            description: None,
            content_type: None,
            ephemeral: None,
            title: None,
            application: None,
            clip_created_at: None,
            clip_participants: None,
        }
    }
}

