/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageEmbedFooterResponse {
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "icon_url", skip_serializing_if = "Option::is_none")]
    pub icon_url: Option<String>,
    #[serde(rename = "proxy_icon_url", skip_serializing_if = "Option::is_none")]
    pub proxy_icon_url: Option<String>,
}

impl MessageEmbedFooterResponse {
    pub fn new(text: String) -> MessageEmbedFooterResponse {
        MessageEmbedFooterResponse {
            text,
            icon_url: None,
            proxy_icon_url: None,
        }
    }
}

