/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageReactionResponse {
    #[serde(rename = "emoji")]
    pub emoji: Box<models::MessageReactionEmojiResponse>,
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(rename = "count_details")]
    pub count_details: Box<models::MessageReactionCountDetailsResponse>,
    #[serde(rename = "burst_colors")]
    pub burst_colors: Vec<String>,
    #[serde(rename = "me_burst")]
    pub me_burst: bool,
    #[serde(rename = "me")]
    pub me: bool,
}

impl MessageReactionResponse {
    pub fn new(emoji: models::MessageReactionEmojiResponse, count: i32, count_details: models::MessageReactionCountDetailsResponse, burst_colors: Vec<String>, me_burst: bool, me: bool) -> MessageReactionResponse {
        MessageReactionResponse {
            emoji: Box::new(emoji),
            count,
            count_details: Box::new(count_details),
            burst_colors,
            me_burst,
            me,
        }
    }
}

