/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageReactionCountDetailsResponse {
    #[serde(rename = "burst")]
    pub burst: i32,
    #[serde(rename = "normal")]
    pub normal: i32,
}

impl MessageReactionCountDetailsResponse {
    pub fn new(burst: i32, normal: i32) -> MessageReactionCountDetailsResponse {
        MessageReactionCountDetailsResponse {
            burst,
            normal,
        }
    }
}

