/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageAttachmentRequest {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "filename", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub filename: Option<Option<String>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "duration_secs", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duration_secs: Option<Option<f64>>,
    #[serde(rename = "waveform", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub waveform: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "is_remix", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_remix: Option<Option<bool>>,
}

impl MessageAttachmentRequest {
    pub fn new(id: String) -> MessageAttachmentRequest {
        MessageAttachmentRequest {
            id,
            filename: None,
            description: None,
            duration_secs: None,
            waveform: None,
            title: None,
            is_remix: None,
        }
    }
}

