/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageEmbedFieldResponse {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "inline")]
    pub inline: bool,
}

impl MessageEmbedFieldResponse {
    pub fn new(name: String, value: String, inline: bool) -> MessageEmbedFieldResponse {
        MessageEmbedFieldResponse {
            name,
            value,
            inline,
        }
    }
}

