/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageReferenceRequest {
    #[serde(rename = "guild_id", skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<String>,
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "message_id")]
    pub message_id: String,
    #[serde(rename = "fail_if_not_exists", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fail_if_not_exists: Option<Option<bool>>,
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<serde_json::Value>>,
}

impl MessageReferenceRequest {
    pub fn new(message_id: String) -> MessageReferenceRequest {
        MessageReferenceRequest {
            guild_id: None,
            channel_id: None,
            message_id,
            fail_if_not_exists: None,
            r#type: None,
        }
    }
}

