/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MessageEmbedProviderResponse {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
}

impl MessageEmbedProviderResponse {
    pub fn new(name: String) -> MessageEmbedProviderResponse {
        MessageEmbedProviderResponse {
            name,
            url: None,
        }
    }
}

