/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinimalContentMessageResponse {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "mentions")]
    pub mentions: Vec<models::UserResponse>,
    #[serde(rename = "mention_roles")]
    pub mention_roles: Vec<String>,
    #[serde(rename = "attachments")]
    pub attachments: Vec<models::MessageAttachmentResponse>,
    #[serde(rename = "embeds")]
    pub embeds: Vec<models::MessageEmbedResponse>,
    #[serde(rename = "timestamp")]
    pub timestamp: String,
    #[serde(rename = "edited_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub edited_timestamp: Option<Option<String>>,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "components")]
    pub components: Vec<models::BasicMessageResponseComponentsInner>,
    #[serde(rename = "stickers", skip_serializing_if = "Option::is_none")]
    pub stickers: Option<Vec<models::GetSticker200Response>>,
    #[serde(rename = "sticker_items", skip_serializing_if = "Option::is_none")]
    pub sticker_items: Option<Vec<models::MessageStickerItemResponse>>,
}

impl MinimalContentMessageResponse {
    pub fn new(r#type: i32, content: String, mentions: Vec<models::UserResponse>, mention_roles: Vec<String>, attachments: Vec<models::MessageAttachmentResponse>, embeds: Vec<models::MessageEmbedResponse>, timestamp: String, flags: i32, components: Vec<models::BasicMessageResponseComponentsInner>) -> MinimalContentMessageResponse {
        MinimalContentMessageResponse {
            r#type,
            content,
            mentions,
            mention_roles,
            attachments,
            embeds,
            timestamp,
            edited_timestamp: None,
            flags,
            components,
            stickers: None,
            sticker_items: None,
        }
    }
}

