/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlSpamUpsertRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "event_type")]
    pub event_type: i32,
    #[serde(rename = "actions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Option<Vec<models::DefaultKeywordListUpsertRequestActionsInner>>>,
    #[serde(rename = "enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<Option<bool>>,
    #[serde(rename = "exempt_roles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exempt_roles: Option<Option<Vec<String>>>,
    #[serde(rename = "exempt_channels", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub exempt_channels: Option<Option<Vec<String>>>,
    #[serde(rename = "trigger_type")]
    pub trigger_type: i32,
    #[serde(rename = "trigger_metadata", skip_serializing_if = "Option::is_none")]
    pub trigger_metadata: Option<serde_json::Value>,
}

impl MlSpamUpsertRequest {
    pub fn new(name: String, event_type: i32, trigger_type: i32) -> MlSpamUpsertRequest {
        MlSpamUpsertRequest {
            name,
            event_type,
            actions: None,
            enabled: None,
            exempt_roles: None,
            exempt_channels: None,
            trigger_type,
            trigger_metadata: None,
        }
    }
}

