/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MlSpamRuleResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "creator_id")]
    pub creator_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "event_type")]
    pub event_type: i32,
    #[serde(rename = "actions")]
    pub actions: Vec<models::DefaultKeywordRuleResponseActionsInner>,
    #[serde(rename = "trigger_type")]
    pub trigger_type: i32,
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "exempt_roles")]
    pub exempt_roles: Vec<String>,
    #[serde(rename = "exempt_channels")]
    pub exempt_channels: Vec<String>,
    #[serde(rename = "trigger_metadata")]
    pub trigger_metadata: serde_json::Value,
}

impl MlSpamRuleResponse {
    pub fn new(id: String, guild_id: String, creator_id: String, name: String, event_type: i32, actions: Vec<models::DefaultKeywordRuleResponseActionsInner>, trigger_type: i32, enabled: bool, exempt_roles: Vec<String>, exempt_channels: Vec<String>, trigger_metadata: serde_json::Value) -> MlSpamRuleResponse {
        MlSpamRuleResponse {
            id,
            guild_id,
            creator_id,
            name,
            event_type,
            actions,
            trigger_type,
            enabled,
            exempt_roles,
            exempt_channels,
            trigger_metadata,
        }
    }
}

