/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModalInteractionCallbackRequestData {
    #[serde(rename = "custom_id")]
    pub custom_id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "components")]
    pub components: Vec<models::ModalInteractionCallbackRequestDataComponentsInner>,
}

impl ModalInteractionCallbackRequestData {
    pub fn new(custom_id: String, title: String, components: Vec<models::ModalInteractionCallbackRequestDataComponentsInner>) -> ModalInteractionCallbackRequestData {
        ModalInteractionCallbackRequestData {
            custom_id,
            title,
            components,
        }
    }
}

