/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NewMemberActionResponse {
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "action_type", deserialize_with = "Option::deserialize")]
    pub action_type: Option<i32>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "emoji", skip_serializing_if = "Option::is_none")]
    pub emoji: Option<Box<models::SettingsEmojiResponse>>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
}

impl NewMemberActionResponse {
    pub fn new(channel_id: String, action_type: Option<i32>, title: String, description: String) -> NewMemberActionResponse {
        NewMemberActionResponse {
            channel_id,
            action_type,
            title,
            description,
            emoji: None,
            icon: None,
        }
    }
}

