/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth2Key {
    #[serde(rename = "kty")]
    pub kty: String,
    #[serde(rename = "use")]
    pub r#use: String,
    #[serde(rename = "kid")]
    pub kid: String,
    #[serde(rename = "n")]
    pub n: String,
    #[serde(rename = "e")]
    pub e: String,
    #[serde(rename = "alg")]
    pub alg: String,
}

impl OAuth2Key {
    pub fn new(kty: String, r#use: String, kid: String, n: String, e: String, alg: String) -> OAuth2Key {
        OAuth2Key {
            kty,
            r#use,
            kid,
            n,
            e,
            alg,
        }
    }
}

