/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OAuth2GetAuthorizationResponse {
    #[serde(rename = "application")]
    pub application: Box<models::ApplicationResponse>,
    #[serde(rename = "expires")]
    pub expires: String,
    #[serde(rename = "scopes")]
    pub scopes: Vec<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::UserResponse>>,
}

impl OAuth2GetAuthorizationResponse {
    pub fn new(application: models::ApplicationResponse, expires: String, scopes: Vec<String>) -> OAuth2GetAuthorizationResponse {
        OAuth2GetAuthorizationResponse {
            application: Box::new(application),
            expires,
            scopes,
            user: None,
        }
    }
}

