/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnboardingPromptResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "options")]
    pub options: Vec<models::OnboardingPromptOptionResponse>,
    #[serde(rename = "single_select")]
    pub single_select: bool,
    #[serde(rename = "required")]
    pub required: bool,
    #[serde(rename = "in_onboarding")]
    pub in_onboarding: bool,
    #[serde(rename = "type")]
    pub r#type: i32,
}

impl OnboardingPromptResponse {
    pub fn new(id: String, title: String, options: Vec<models::OnboardingPromptOptionResponse>, single_select: bool, required: bool, in_onboarding: bool, r#type: i32) -> OnboardingPromptResponse {
        OnboardingPromptResponse {
            id,
            title,
            options,
            single_select,
            required,
            in_onboarding,
            r#type,
        }
    }
}

