/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnboardingPromptOptionRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "emoji_id", skip_serializing_if = "Option::is_none")]
    pub emoji_id: Option<String>,
    #[serde(rename = "emoji_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emoji_name: Option<Option<String>>,
    #[serde(rename = "emoji_animated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emoji_animated: Option<Option<bool>>,
    #[serde(rename = "role_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub role_ids: Option<Option<Vec<String>>>,
    #[serde(rename = "channel_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub channel_ids: Option<Option<Vec<String>>>,
}

impl OnboardingPromptOptionRequest {
    pub fn new(title: String) -> OnboardingPromptOptionRequest {
        OnboardingPromptOptionRequest {
            id: None,
            title,
            description: None,
            emoji_id: None,
            emoji_name: None,
            emoji_animated: None,
            role_ids: None,
            channel_ids: None,
        }
    }
}

