/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OnboardingPromptOptionResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "emoji")]
    pub emoji: Box<models::SettingsEmojiResponse>,
    #[serde(rename = "role_ids")]
    pub role_ids: Vec<String>,
    #[serde(rename = "channel_ids")]
    pub channel_ids: Vec<String>,
}

impl OnboardingPromptOptionResponse {
    pub fn new(id: String, title: String, description: String, emoji: models::SettingsEmojiResponse, role_ids: Vec<String>, channel_ids: Vec<String>) -> OnboardingPromptOptionResponse {
        OnboardingPromptOptionResponse {
            id,
            title,
            description,
            emoji: Box::new(emoji),
            role_ids,
            channel_ids,
        }
    }
}

