/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PinnedMessagesResponse {
    #[serde(rename = "items")]
    pub items: Vec<models::PinnedMessageResponse>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
}

impl PinnedMessagesResponse {
    pub fn new(items: Vec<models::PinnedMessageResponse>, has_more: bool) -> PinnedMessagesResponse {
        PinnedMessagesResponse {
            items,
            has_more,
        }
    }
}

