/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PinnedMessageResponse {
    #[serde(rename = "pinned_at")]
    pub pinned_at: String,
    #[serde(rename = "message")]
    pub message: Box<models::MessageResponse>,
}

impl PinnedMessageResponse {
    pub fn new(pinned_at: String, message: models::MessageResponse) -> PinnedMessageResponse {
        PinnedMessageResponse {
            pinned_at,
            message: Box::new(message),
        }
    }
}

