/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PollAnswerResponse {
    #[serde(rename = "answer_id")]
    pub answer_id: i32,
    #[serde(rename = "poll_media")]
    pub poll_media: Box<models::PollMediaResponse>,
}

impl PollAnswerResponse {
    pub fn new(answer_id: i32, poll_media: models::PollMediaResponse) -> PollAnswerResponse {
        PollAnswerResponse {
            answer_id,
            poll_media: Box::new(poll_media),
        }
    }
}

