/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PollResponse {
    #[serde(rename = "question")]
    pub question: Box<models::PollMediaResponse>,
    #[serde(rename = "answers")]
    pub answers: Vec<models::PollAnswerResponse>,
    #[serde(rename = "expiry")]
    pub expiry: String,
    #[serde(rename = "allow_multiselect")]
    pub allow_multiselect: bool,
    #[serde(rename = "layout_type")]
    pub layout_type: i32,
    #[serde(rename = "results")]
    pub results: Box<models::PollResultsResponse>,
}

impl PollResponse {
    pub fn new(question: models::PollMediaResponse, answers: Vec<models::PollAnswerResponse>, expiry: String, allow_multiselect: bool, layout_type: i32, results: models::PollResultsResponse) -> PollResponse {
        PollResponse {
            question: Box::new(question),
            answers,
            expiry,
            allow_multiselect,
            layout_type,
            results: Box::new(results),
        }
    }
}

