/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PollAnswerCreateRequest {
    #[serde(rename = "poll_media")]
    pub poll_media: Box<models::PollMediaCreateRequest>,
}

impl PollAnswerCreateRequest {
    pub fn new(poll_media: models::PollMediaCreateRequest) -> PollAnswerCreateRequest {
        PollAnswerCreateRequest {
            poll_media: Box::new(poll_media),
        }
    }
}

