/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateChannelLocation {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "channel_id")]
    pub channel_id: String,
}

impl PrivateChannelLocation {
    pub fn new(id: String, kind: String, channel_id: String) -> PrivateChannelLocation {
        PrivateChannelLocation {
            id,
            kind,
            channel_id,
        }
    }
}

