/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateGuildMemberResponse {
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
    #[serde(rename = "avatar_decoration_data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_decoration_data: Option<Option<Box<models::UserAvatarDecorationResponse>>>,
    #[serde(rename = "banner", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub banner: Option<Option<String>>,
    #[serde(rename = "communication_disabled_until", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub communication_disabled_until: Option<Option<String>>,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "joined_at")]
    pub joined_at: String,
    #[serde(rename = "nick", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nick: Option<Option<String>>,
    #[serde(rename = "pending")]
    pub pending: bool,
    #[serde(rename = "premium_since", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub premium_since: Option<Option<String>>,
    #[serde(rename = "roles")]
    pub roles: Vec<String>,
    #[serde(rename = "collectibles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub collectibles: Option<Option<Box<models::UserCollectiblesResponse>>>,
    #[serde(rename = "user")]
    pub user: Box<models::UserResponse>,
    #[serde(rename = "mute")]
    pub mute: bool,
    #[serde(rename = "deaf")]
    pub deaf: bool,
    #[serde(rename = "permissions", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<String>,
}

impl PrivateGuildMemberResponse {
    pub fn new(flags: i32, joined_at: String, pending: bool, roles: Vec<String>, user: models::UserResponse, mute: bool, deaf: bool) -> PrivateGuildMemberResponse {
        PrivateGuildMemberResponse {
            avatar: None,
            avatar_decoration_data: None,
            banner: None,
            communication_disabled_until: None,
            flags,
            joined_at,
            nick: None,
            pending,
            premium_since: None,
            roles,
            collectibles: None,
            user: Box::new(user),
            mute,
            deaf,
            permissions: None,
        }
    }
}

