/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateGroupChannelResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "last_message_id", skip_serializing_if = "Option::is_none")]
    pub last_message_id: Option<String>,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "last_pin_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_pin_timestamp: Option<Option<String>>,
    #[serde(rename = "recipients")]
    pub recipients: Vec<models::UserResponse>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "owner_id")]
    pub owner_id: String,
    #[serde(rename = "managed", skip_serializing_if = "Option::is_none")]
    pub managed: Option<bool>,
    #[serde(rename = "application_id", skip_serializing_if = "Option::is_none")]
    pub application_id: Option<String>,
}

impl PrivateGroupChannelResponse {
    pub fn new(id: String, r#type: i32, flags: i32, recipients: Vec<models::UserResponse>, owner_id: String) -> PrivateGroupChannelResponse {
        PrivateGroupChannelResponse {
            id,
            r#type,
            last_message_id: None,
            flags,
            last_pin_timestamp: None,
            recipients,
            name: None,
            icon: None,
            owner_id,
            managed: None,
            application_id: None,
        }
    }
}

