/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateChannelResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "last_message_id", skip_serializing_if = "Option::is_none")]
    pub last_message_id: Option<String>,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "last_pin_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_pin_timestamp: Option<Option<String>>,
    #[serde(rename = "recipients")]
    pub recipients: Vec<models::UserResponse>,
}

impl PrivateChannelResponse {
    pub fn new(id: String, r#type: i32, flags: i32, recipients: Vec<models::UserResponse>) -> PrivateChannelResponse {
        PrivateChannelResponse {
            id,
            r#type,
            last_message_id: None,
            flags,
            last_pin_timestamp: None,
            recipients,
        }
    }
}

