/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProvisionalTokenResponse {
    #[serde(rename = "token_type")]
    pub token_type: String,
    #[serde(rename = "access_token")]
    pub access_token: String,
    #[serde(rename = "expires_in")]
    pub expires_in: i32,
    #[serde(rename = "scope")]
    pub scope: String,
    #[serde(rename = "id_token")]
    pub id_token: String,
    #[serde(rename = "refresh_token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub refresh_token: Option<Option<String>>,
    #[serde(rename = "scopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Option<Vec<String>>>,
    #[serde(rename = "expires_at_s", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub expires_at_s: Option<Option<i32>>,
}

impl ProvisionalTokenResponse {
    pub fn new(token_type: String, access_token: String, expires_in: i32, scope: String, id_token: String) -> ProvisionalTokenResponse {
        ProvisionalTokenResponse {
            token_type,
            access_token,
            expires_in,
            scope,
            id_token,
            refresh_token: None,
            scopes: None,
            expires_at_s: None,
        }
    }
}

