/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PruneGuildRequest {
    #[serde(rename = "days", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub days: Option<Option<i32>>,
    #[serde(rename = "compute_prune_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub compute_prune_count: Option<Option<bool>>,
    #[serde(rename = "include_roles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub include_roles: Option<Option<Box<models::PruneGuildRequestIncludeRoles>>>,
}

impl PruneGuildRequest {
    pub fn new() -> PruneGuildRequest {
        PruneGuildRequest {
            days: None,
            compute_prune_count: None,
            include_roles: None,
        }
    }
}

