/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PurchaseNotificationResponse {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<i32>,
    #[serde(rename = "guild_product_purchase", skip_serializing_if = "Option::is_none")]
    pub guild_product_purchase: Option<Box<models::GuildProductPurchaseResponse>>,
}

impl PurchaseNotificationResponse {
    pub fn new(r#type: Option<i32>) -> PurchaseNotificationResponse {
        PurchaseNotificationResponse {
            r#type,
            guild_product_purchase: None,
        }
    }
}

