/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RatelimitedResponse : Ratelimit error object returned by the Discord API
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RatelimitedResponse {
    /// Discord internal error code. See error code reference
    #[serde(rename = "code")]
    pub code: i32,
    /// Human-readable error message
    #[serde(rename = "message")]
    pub message: String,
    /// The number of seconds to wait before retrying your request
    #[serde(rename = "retry_after")]
    pub retry_after: f64,
    /// Whether you are being ratelimited by the global ratelimit or a per-endpoint ratelimit
    #[serde(rename = "global")]
    pub global: bool,
}

impl RatelimitedResponse {
    /// Ratelimit error object returned by the Discord API
    pub fn new(code: i32, message: String, retry_after: f64, global: bool) -> RatelimitedResponse {
        RatelimitedResponse {
            code,
            message,
            retry_after,
            global,
        }
    }
}

