/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResourceChannelResponse {
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "emoji", skip_serializing_if = "Option::is_none")]
    pub emoji: Option<Box<models::SettingsEmojiResponse>>,
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(rename = "description")]
    pub description: String,
}

impl ResourceChannelResponse {
    pub fn new(channel_id: String, title: String, description: String) -> ResourceChannelResponse {
        ResourceChannelResponse {
            channel_id,
            title,
            emoji: None,
            icon: None,
            description,
        }
    }
}

