/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResolvedObjectsResponse {
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<std::collections::HashMap<String, models::UserResponse>>,
    #[serde(rename = "members", skip_serializing_if = "Option::is_none")]
    pub members: Option<std::collections::HashMap<String, models::BasicGuildMemberResponse>>,
    #[serde(rename = "channels", skip_serializing_if = "Option::is_none")]
    pub channels: Option<std::collections::HashMap<String, models::GetChannel200Response>>,
    #[serde(rename = "roles", skip_serializing_if = "Option::is_none")]
    pub roles: Option<std::collections::HashMap<String, models::GuildRoleResponse>>,
}

impl ResolvedObjectsResponse {
    pub fn new() -> ResolvedObjectsResponse {
        ResolvedObjectsResponse {
            users: None,
            members: None,
            channels: None,
            roles: None,
        }
    }
}

