/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RichEmbedImage {
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
    #[serde(rename = "width", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub width: Option<Option<i32>>,
    #[serde(rename = "height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub height: Option<Option<i32>>,
    #[serde(rename = "placeholder", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<Option<String>>,
    #[serde(rename = "placeholder_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub placeholder_version: Option<Option<i32>>,
    #[serde(rename = "is_animated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_animated: Option<Option<bool>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
}

impl RichEmbedImage {
    pub fn new() -> RichEmbedImage {
        RichEmbedImage {
            url: None,
            width: None,
            height: None,
            placeholder: None,
            placeholder_version: None,
            is_animated: None,
            description: None,
        }
    }
}

