/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RoleSelectComponentForMessageRequest {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    #[serde(rename = "custom_id")]
    pub custom_id: String,
    #[serde(rename = "placeholder", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<Option<String>>,
    #[serde(rename = "min_values", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_values: Option<Option<i32>>,
    #[serde(rename = "max_values", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_values: Option<Option<i32>>,
    #[serde(rename = "disabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub disabled: Option<Option<bool>>,
    #[serde(rename = "required", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub required: Option<Option<bool>>,
    #[serde(rename = "default_values", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_values: Option<Option<Vec<models::RoleSelectDefaultValue>>>,
}

impl RoleSelectComponentForMessageRequest {
    pub fn new(r#type: i32, custom_id: String) -> RoleSelectComponentForMessageRequest {
        RoleSelectComponentForMessageRequest {
            r#type,
            id: None,
            custom_id,
            placeholder: None,
            min_values: None,
            max_values: None,
            disabled: None,
            required: None,
            default_values: None,
        }
    }
}

