/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SdkMessageRequest {
    #[serde(rename = "content", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content: Option<Option<String>>,
    #[serde(rename = "embeds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub embeds: Option<Option<Vec<models::RichEmbed>>>,
    #[serde(rename = "allowed_mentions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_mentions: Option<Option<Box<models::MessageAllowedMentionsRequest>>>,
    #[serde(rename = "sticker_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sticker_ids: Option<Option<Vec<String>>>,
    #[serde(rename = "components", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub components: Option<Option<Vec<models::BaseCreateMessageCreateRequestComponentsInner>>>,
    #[serde(rename = "flags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Option<i32>>,
    #[serde(rename = "attachments", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Option<Vec<models::MessageAttachmentRequest>>>,
    #[serde(rename = "poll", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub poll: Option<Option<Box<models::PollCreateRequest>>>,
    #[serde(rename = "shared_client_theme", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub shared_client_theme: Option<Option<Box<models::CustomClientThemeShareRequest>>>,
    #[serde(rename = "confetti_potion", skip_serializing_if = "Option::is_none")]
    pub confetti_potion: Option<serde_json::Value>,
    #[serde(rename = "message_reference", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message_reference: Option<Option<Box<models::MessageReferenceRequest>>>,
    #[serde(rename = "nonce", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub nonce: Option<Option<Box<models::BasicMessageResponseNonce>>>,
    #[serde(rename = "enforce_nonce", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enforce_nonce: Option<Option<bool>>,
    #[serde(rename = "tts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tts: Option<Option<bool>>,
}

impl SdkMessageRequest {
    pub fn new() -> SdkMessageRequest {
        SdkMessageRequest {
            content: None,
            embeds: None,
            allowed_mentions: None,
            sticker_ids: None,
            components: None,
            flags: None,
            attachments: None,
            poll: None,
            shared_client_theme: None,
            confetti_potion: None,
            message_reference: None,
            nonce: None,
            enforce_nonce: None,
            tts: None,
        }
    }
}

