/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SectionComponentForMessageRequest {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    #[serde(rename = "components")]
    pub components: Vec<models::TextDisplayComponentForMessageRequest>,
    #[serde(rename = "accessory")]
    pub accessory: Box<models::SectionComponentForMessageRequestAccessory>,
}

impl SectionComponentForMessageRequest {
    pub fn new(r#type: i32, components: Vec<models::TextDisplayComponentForMessageRequest>, accessory: models::SectionComponentForMessageRequestAccessory) -> SectionComponentForMessageRequest {
        SectionComponentForMessageRequest {
            r#type,
            id: None,
            components,
            accessory: Box::new(accessory),
        }
    }
}

