/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeparatorComponentResponse {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "spacing")]
    pub spacing: i32,
    #[serde(rename = "divider")]
    pub divider: bool,
}

impl SeparatorComponentResponse {
    pub fn new(r#type: i32, id: i32, spacing: i32, divider: bool) -> SeparatorComponentResponse {
        SeparatorComponentResponse {
            r#type,
            id,
            spacing,
            divider,
        }
    }
}

