/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SoundboardSoundSendRequest {
    #[serde(rename = "sound_id")]
    pub sound_id: String,
    #[serde(rename = "source_guild_id", skip_serializing_if = "Option::is_none")]
    pub source_guild_id: Option<String>,
}

impl SoundboardSoundSendRequest {
    pub fn new(sound_id: String) -> SoundboardSoundSendRequest {
        SoundboardSoundSendRequest {
            sound_id,
            source_guild_id: None,
        }
    }
}

