/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StageInstanceResponse {
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "channel_id")]
    pub channel_id: String,
    #[serde(rename = "topic")]
    pub topic: String,
    #[serde(rename = "privacy_level")]
    pub privacy_level: i32,
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "discoverable_disabled")]
    pub discoverable_disabled: bool,
    #[serde(rename = "guild_scheduled_event_id", skip_serializing_if = "Option::is_none")]
    pub guild_scheduled_event_id: Option<String>,
}

impl StageInstanceResponse {
    pub fn new(guild_id: String, channel_id: String, topic: String, privacy_level: i32, id: String, discoverable_disabled: bool) -> StageInstanceResponse {
        StageInstanceResponse {
            guild_id,
            channel_id,
            topic,
            privacy_level,
            id,
            discoverable_disabled,
            guild_scheduled_event_id: None,
        }
    }
}

