/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StandardStickerResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "tags")]
    pub tags: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "format_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub format_type: Option<Option<i32>>,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "pack_id")]
    pub pack_id: String,
    #[serde(rename = "sort_value")]
    pub sort_value: i32,
}

impl StandardStickerResponse {
    pub fn new(id: String, name: String, tags: String, r#type: i32, pack_id: String, sort_value: i32) -> StandardStickerResponse {
        StandardStickerResponse {
            id,
            name,
            tags,
            r#type,
            format_type: None,
            description: None,
            pack_id,
            sort_value,
        }
    }
}

