/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StickerPackResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "sku_id")]
    pub sku_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "stickers")]
    pub stickers: Vec<models::StandardStickerResponse>,
    #[serde(rename = "cover_sticker_id", skip_serializing_if = "Option::is_none")]
    pub cover_sticker_id: Option<String>,
    #[serde(rename = "banner_asset_id", skip_serializing_if = "Option::is_none")]
    pub banner_asset_id: Option<String>,
}

impl StickerPackResponse {
    pub fn new(id: String, sku_id: String, name: String, stickers: Vec<models::StandardStickerResponse>) -> StickerPackResponse {
        StickerPackResponse {
            id,
            sku_id,
            name,
            description: None,
            stickers,
            cover_sticker_id: None,
            banner_asset_id: None,
        }
    }
}

