/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StickerPackCollectionResponse {
    #[serde(rename = "sticker_packs")]
    pub sticker_packs: Vec<models::StickerPackResponse>,
}

impl StickerPackCollectionResponse {
    pub fn new(sticker_packs: Vec<models::StickerPackResponse>) -> StickerPackCollectionResponse {
        StickerPackCollectionResponse {
            sticker_packs,
        }
    }
}

