/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub icon: Option<Option<String>>,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "owner_user_id")]
    pub owner_user_id: String,
    #[serde(rename = "members")]
    pub members: Vec<models::TeamMemberResponse>,
}

impl TeamResponse {
    pub fn new(id: String, name: String, owner_user_id: String, members: Vec<models::TeamMemberResponse>) -> TeamResponse {
        TeamResponse {
            id,
            icon: None,
            name,
            owner_user_id,
            members,
        }
    }
}

