/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TeamMemberResponse {
    #[serde(rename = "user")]
    pub user: Box<models::UserResponse>,
    #[serde(rename = "team_id")]
    pub team_id: String,
    #[serde(rename = "membership_state")]
    pub membership_state: i32,
}

impl TeamMemberResponse {
    pub fn new(user: models::UserResponse, team_id: String, membership_state: i32) -> TeamMemberResponse {
        TeamMemberResponse {
            user: Box::new(user),
            team_id,
            membership_state,
        }
    }
}

