/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TextInputComponentForModalRequest {
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    #[serde(rename = "custom_id")]
    pub custom_id: String,
    #[serde(rename = "style")]
    pub style: i32,
    #[serde(rename = "label", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub label: Option<Option<String>>,
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<String>>,
    #[serde(rename = "placeholder", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub placeholder: Option<Option<String>>,
    #[serde(rename = "required", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub required: Option<Option<bool>>,
    #[serde(rename = "min_length", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub min_length: Option<Option<i32>>,
    #[serde(rename = "max_length", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_length: Option<Option<i32>>,
}

impl TextInputComponentForModalRequest {
    pub fn new(r#type: i32, custom_id: String, style: i32) -> TextInputComponentForModalRequest {
        TextInputComponentForModalRequest {
            r#type,
            id: None,
            custom_id,
            style,
            label: None,
            value: None,
            placeholder: None,
            required: None,
            min_length: None,
            max_length: None,
        }
    }
}

