/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadMemberResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
    #[serde(rename = "join_timestamp")]
    pub join_timestamp: String,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "member", skip_serializing_if = "Option::is_none")]
    pub member: Option<Box<models::GuildMemberResponse>>,
}

impl ThreadMemberResponse {
    pub fn new(id: String, user_id: String, join_timestamp: String, flags: i32) -> ThreadMemberResponse {
        ThreadMemberResponse {
            id,
            user_id,
            join_timestamp,
            flags,
            member: None,
        }
    }
}

