/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "type")]
    pub r#type: i32,
    #[serde(rename = "last_message_id", skip_serializing_if = "Option::is_none")]
    pub last_message_id: Option<String>,
    #[serde(rename = "flags")]
    pub flags: i32,
    #[serde(rename = "last_pin_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_pin_timestamp: Option<Option<String>>,
    #[serde(rename = "guild_id")]
    pub guild_id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "parent_id", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "rate_limit_per_user", skip_serializing_if = "Option::is_none")]
    pub rate_limit_per_user: Option<i32>,
    #[serde(rename = "bitrate", skip_serializing_if = "Option::is_none")]
    pub bitrate: Option<i32>,
    #[serde(rename = "user_limit", skip_serializing_if = "Option::is_none")]
    pub user_limit: Option<i32>,
    #[serde(rename = "rtc_region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rtc_region: Option<Option<String>>,
    #[serde(rename = "video_quality_mode", skip_serializing_if = "Option::is_none")]
    pub video_quality_mode: Option<i32>,
    #[serde(rename = "permissions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub permissions: Option<Option<String>>,
    #[serde(rename = "owner_id")]
    pub owner_id: String,
    #[serde(rename = "thread_metadata")]
    pub thread_metadata: Box<models::ThreadMetadataResponse>,
    #[serde(rename = "message_count")]
    pub message_count: i32,
    #[serde(rename = "member_count")]
    pub member_count: i32,
    #[serde(rename = "total_message_sent")]
    pub total_message_sent: i32,
    #[serde(rename = "applied_tags", skip_serializing_if = "Option::is_none")]
    pub applied_tags: Option<Vec<String>>,
    #[serde(rename = "member", skip_serializing_if = "Option::is_none")]
    pub member: Option<Box<models::ThreadMemberResponse>>,
}

impl ThreadResponse {
    pub fn new(id: String, r#type: i32, flags: i32, guild_id: String, name: String, owner_id: String, thread_metadata: models::ThreadMetadataResponse, message_count: i32, member_count: i32, total_message_sent: i32) -> ThreadResponse {
        ThreadResponse {
            id,
            r#type,
            last_message_id: None,
            flags,
            last_pin_timestamp: None,
            guild_id,
            name,
            parent_id: None,
            rate_limit_per_user: None,
            bitrate: None,
            user_limit: None,
            rtc_region: None,
            video_quality_mode: None,
            permissions: None,
            owner_id,
            thread_metadata: Box::new(thread_metadata),
            message_count,
            member_count,
            total_message_sent,
            applied_tags: None,
            member: None,
        }
    }
}

