/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum ThreadSearchTagParameter {
    String(String),
    ArraynullString(Vec<String>),
}

impl Default for ThreadSearchTagParameter {
    fn default() -> Self {
        Self::String(Default::default())
    }
}

