/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadMetadataResponse {
    #[serde(rename = "archived")]
    pub archived: bool,
    #[serde(rename = "archive_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub archive_timestamp: Option<Option<String>>,
    #[serde(rename = "auto_archive_duration")]
    pub auto_archive_duration: i32,
    #[serde(rename = "locked")]
    pub locked: bool,
    #[serde(rename = "create_timestamp", skip_serializing_if = "Option::is_none")]
    pub create_timestamp: Option<String>,
    #[serde(rename = "invitable", skip_serializing_if = "Option::is_none")]
    pub invitable: Option<bool>,
}

impl ThreadMetadataResponse {
    pub fn new(archived: bool, auto_archive_duration: i32, locked: bool) -> ThreadMetadataResponse {
        ThreadMetadataResponse {
            archived,
            archive_timestamp: None,
            auto_archive_duration,
            locked,
            create_timestamp: None,
            invitable: None,
        }
    }
}

