/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ThreadSearchResponse {
    #[serde(rename = "threads")]
    pub threads: Vec<models::ThreadResponse>,
    #[serde(rename = "members")]
    pub members: Vec<models::ThreadMemberResponse>,
    #[serde(rename = "has_more")]
    pub has_more: bool,
    #[serde(rename = "first_messages", skip_serializing_if = "Option::is_none")]
    pub first_messages: Option<Vec<models::MessageResponse>>,
    #[serde(rename = "total_results")]
    pub total_results: i32,
}

impl ThreadSearchResponse {
    pub fn new(threads: Vec<models::ThreadResponse>, members: Vec<models::ThreadMemberResponse>, has_more: bool, total_results: i32) -> ThreadSearchResponse {
        ThreadSearchResponse {
            threads,
            members,
            has_more,
            first_messages: None,
            total_results,
        }
    }
}

