/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnfurledMediaResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "proxy_url")]
    pub proxy_url: String,
    #[serde(rename = "width", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub width: Option<Option<i32>>,
    #[serde(rename = "height", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub height: Option<Option<i32>>,
    #[serde(rename = "content_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<Option<String>>,
    #[serde(rename = "attachment_id", skip_serializing_if = "Option::is_none")]
    pub attachment_id: Option<String>,
}

impl UnfurledMediaResponse {
    pub fn new(id: String, url: String, proxy_url: String) -> UnfurledMediaResponse {
        UnfurledMediaResponse {
            id,
            url,
            proxy_url,
            width: None,
            height: None,
            content_type: None,
            attachment_id: None,
        }
    }
}

