/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateOnboardingPromptRequest {
    #[serde(rename = "title")]
    pub title: String,
    #[serde(rename = "options")]
    pub options: Vec<models::OnboardingPromptOptionRequest>,
    #[serde(rename = "single_select", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub single_select: Option<Option<bool>>,
    #[serde(rename = "required", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub required: Option<Option<bool>>,
    #[serde(rename = "in_onboarding", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_onboarding: Option<Option<bool>>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    #[serde(rename = "id")]
    pub id: String,
}

impl UpdateOnboardingPromptRequest {
    pub fn new(title: String, options: Vec<models::OnboardingPromptOptionRequest>, id: String) -> UpdateOnboardingPromptRequest {
        UpdateOnboardingPromptRequest {
            title,
            options,
            single_select: None,
            required: None,
            in_onboarding: None,
            r#type: None,
            id,
        }
    }
}

