/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateThreadRequestPartial {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "archived", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub archived: Option<Option<bool>>,
    #[serde(rename = "locked", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub locked: Option<Option<bool>>,
    #[serde(rename = "invitable", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub invitable: Option<Option<bool>>,
    #[serde(rename = "auto_archive_duration", skip_serializing_if = "Option::is_none")]
    pub auto_archive_duration: Option<i32>,
    #[serde(rename = "rate_limit_per_user", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rate_limit_per_user: Option<Option<i32>>,
    #[serde(rename = "flags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub flags: Option<Option<i32>>,
    #[serde(rename = "applied_tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub applied_tags: Option<Option<Vec<String>>>,
    #[serde(rename = "bitrate", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub bitrate: Option<Option<i32>>,
    #[serde(rename = "user_limit", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub user_limit: Option<Option<i32>>,
    #[serde(rename = "rtc_region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rtc_region: Option<Option<String>>,
    #[serde(rename = "video_quality_mode", skip_serializing_if = "Option::is_none")]
    pub video_quality_mode: Option<i32>,
}

impl UpdateThreadRequestPartial {
    pub fn new() -> UpdateThreadRequestPartial {
        UpdateThreadRequestPartial {
            name: None,
            archived: None,
            locked: None,
            invitable: None,
            auto_archive_duration: None,
            rate_limit_per_user: None,
            flags: None,
            applied_tags: None,
            bitrate: None,
            user_limit: None,
            rtc_region: None,
            video_quality_mode: None,
        }
    }
}

