/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateThreadTagRequest {
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "emoji_id", skip_serializing_if = "Option::is_none")]
    pub emoji_id: Option<String>,
    #[serde(rename = "emoji_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emoji_name: Option<Option<String>>,
    #[serde(rename = "moderated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub moderated: Option<Option<bool>>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
}

impl UpdateThreadTagRequest {
    pub fn new(name: String) -> UpdateThreadTagRequest {
        UpdateThreadTagRequest {
            name,
            emoji_id: None,
            emoji_name: None,
            moderated: None,
            id: None,
        }
    }
}

