/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAutoModerationRuleRequest {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<i32>,
    #[serde(rename = "actions", skip_serializing_if = "Option::is_none")]
    pub actions: Option<Vec<models::DefaultKeywordListUpsertRequestActionsInner>>,
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "exempt_roles", skip_serializing_if = "Option::is_none")]
    pub exempt_roles: Option<Vec<String>>,
    #[serde(rename = "exempt_channels", skip_serializing_if = "Option::is_none")]
    pub exempt_channels: Option<Vec<String>>,
    #[serde(rename = "trigger_type", skip_serializing_if = "Option::is_none")]
    pub trigger_type: Option<i32>,
    #[serde(rename = "trigger_metadata", skip_serializing_if = "Option::is_none")]
    pub trigger_metadata: Option<Box<models::MentionSpamTriggerMetadata>>,
}

impl UpdateAutoModerationRuleRequest {
    pub fn new() -> UpdateAutoModerationRuleRequest {
        UpdateAutoModerationRuleRequest {
            name: None,
            event_type: None,
            actions: None,
            enabled: None,
            exempt_roles: None,
            exempt_channels: None,
            trigger_type: None,
            trigger_metadata: None,
        }
    }
}

