/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateSelfVoiceStateRequestPartial {
    #[serde(rename = "request_to_speak_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub request_to_speak_timestamp: Option<Option<String>>,
    #[serde(rename = "suppress", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub suppress: Option<Option<bool>>,
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
}

impl UpdateSelfVoiceStateRequestPartial {
    pub fn new() -> UpdateSelfVoiceStateRequestPartial {
        UpdateSelfVoiceStateRequestPartial {
            request_to_speak_timestamp: None,
            suppress: None,
            channel_id: None,
        }
    }
}

