/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateStageInstanceRequest {
    #[serde(rename = "topic", skip_serializing_if = "Option::is_none")]
    pub topic: Option<String>,
    #[serde(rename = "privacy_level", skip_serializing_if = "Option::is_none")]
    pub privacy_level: Option<i32>,
}

impl UpdateStageInstanceRequest {
    pub fn new() -> UpdateStageInstanceRequest {
        UpdateStageInstanceRequest {
            topic: None,
            privacy_level: None,
        }
    }
}

