/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGuildScheduledEventRequest {
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(rename = "scheduled_start_time", skip_serializing_if = "Option::is_none")]
    pub scheduled_start_time: Option<String>,
    #[serde(rename = "scheduled_end_time", skip_serializing_if = "Option::is_none")]
    pub scheduled_end_time: Option<String>,
    #[serde(rename = "entity_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub entity_type: Option<Option<i32>>,
    #[serde(rename = "privacy_level", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub privacy_level: Option<Option<serde_json::Value>>,
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "entity_metadata", skip_serializing_if = "Option::is_none")]
    pub entity_metadata: Option<serde_json::Value>,
}

impl UpdateGuildScheduledEventRequest {
    pub fn new() -> UpdateGuildScheduledEventRequest {
        UpdateGuildScheduledEventRequest {
            status: None,
            name: None,
            description: None,
            image: None,
            scheduled_start_time: None,
            scheduled_end_time: None,
            entity_type: None,
            privacy_level: None,
            channel_id: None,
            entity_metadata: None,
        }
    }
}

