/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserPrimaryGuildResponse {
    #[serde(rename = "identity_guild_id", skip_serializing_if = "Option::is_none")]
    pub identity_guild_id: Option<String>,
    #[serde(rename = "identity_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub identity_enabled: Option<Option<bool>>,
    #[serde(rename = "tag", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tag: Option<Option<String>>,
    #[serde(rename = "badge", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub badge: Option<Option<String>>,
}

impl UserPrimaryGuildResponse {
    pub fn new() -> UserPrimaryGuildResponse {
        UserPrimaryGuildResponse {
            identity_guild_id: None,
            identity_enabled: None,
            tag: None,
            badge: None,
        }
    }
}

