/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserCommunicationDisabledActionMetadata {
    #[serde(rename = "duration_seconds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub duration_seconds: Option<Option<i32>>,
}

impl UserCommunicationDisabledActionMetadata {
    pub fn new() -> UserCommunicationDisabledActionMetadata {
        UserCommunicationDisabledActionMetadata {
            duration_seconds: None,
        }
    }
}

