/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserAvatarDecorationResponse {
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "sku_id", skip_serializing_if = "Option::is_none")]
    pub sku_id: Option<String>,
}

impl UserAvatarDecorationResponse {
    pub fn new(asset: String) -> UserAvatarDecorationResponse {
        UserAvatarDecorationResponse {
            asset,
            sku_id: None,
        }
    }
}

