/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserNameplateResponse {
    #[serde(rename = "sku_id", skip_serializing_if = "Option::is_none")]
    pub sku_id: Option<String>,
    #[serde(rename = "asset")]
    pub asset: String,
    #[serde(rename = "label")]
    pub label: String,
    #[serde(rename = "palette")]
    pub palette: String,
}

impl UserNameplateResponse {
    pub fn new(asset: String, label: String, palette: String) -> UserNameplateResponse {
        UserNameplateResponse {
            sku_id: None,
            asset,
            label,
            palette,
        }
    }
}

