/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UserResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "avatar", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<Option<String>>,
    #[serde(rename = "discriminator")]
    pub discriminator: String,
    #[serde(rename = "public_flags")]
    pub public_flags: i32,
    #[serde(rename = "flags")]
    pub flags: i64,
    #[serde(rename = "bot", skip_serializing_if = "Option::is_none")]
    pub bot: Option<bool>,
    #[serde(rename = "system", skip_serializing_if = "Option::is_none")]
    pub system: Option<bool>,
    #[serde(rename = "banner", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub banner: Option<Option<String>>,
    #[serde(rename = "accent_color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub accent_color: Option<Option<i32>>,
    #[serde(rename = "global_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub global_name: Option<Option<String>>,
    #[serde(rename = "avatar_decoration_data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub avatar_decoration_data: Option<Option<Box<models::UserAvatarDecorationResponse>>>,
    #[serde(rename = "collectibles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub collectibles: Option<Option<Box<models::UserCollectiblesResponse>>>,
    #[serde(rename = "primary_guild", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub primary_guild: Option<Option<Box<models::UserPrimaryGuildResponse>>>,
}

impl UserResponse {
    pub fn new(id: String, username: String, discriminator: String, public_flags: i32, flags: i64) -> UserResponse {
        UserResponse {
            id,
            username,
            avatar: None,
            discriminator,
            public_flags,
            flags,
            bot: None,
            system: None,
            banner: None,
            accent_color: None,
            global_name: None,
            avatar_decoration_data: None,
            collectibles: None,
            primary_guild: None,
        }
    }
}

