/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoiceRegionResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "custom")]
    pub custom: bool,
    #[serde(rename = "deprecated")]
    pub deprecated: bool,
    #[serde(rename = "optimal")]
    pub optimal: bool,
}

impl VoiceRegionResponse {
    pub fn new(id: String, name: String, custom: bool, deprecated: bool, optimal: bool) -> VoiceRegionResponse {
        VoiceRegionResponse {
            id,
            name,
            custom,
            deprecated,
            optimal,
        }
    }
}

