/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VoiceStateResponse {
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
    #[serde(rename = "deaf")]
    pub deaf: bool,
    #[serde(rename = "guild_id", skip_serializing_if = "Option::is_none")]
    pub guild_id: Option<String>,
    #[serde(rename = "member", skip_serializing_if = "Option::is_none")]
    pub member: Option<Box<models::GuildMemberResponse>>,
    #[serde(rename = "mute")]
    pub mute: bool,
    #[serde(rename = "request_to_speak_timestamp", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub request_to_speak_timestamp: Option<Option<String>>,
    #[serde(rename = "suppress")]
    pub suppress: bool,
    #[serde(rename = "self_stream", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub self_stream: Option<Option<bool>>,
    #[serde(rename = "self_deaf")]
    pub self_deaf: bool,
    #[serde(rename = "self_mute")]
    pub self_mute: bool,
    #[serde(rename = "self_video")]
    pub self_video: bool,
    #[serde(rename = "session_id")]
    pub session_id: String,
    #[serde(rename = "user_id")]
    pub user_id: String,
}

impl VoiceStateResponse {
    pub fn new(deaf: bool, mute: bool, suppress: bool, self_deaf: bool, self_mute: bool, self_video: bool, session_id: String, user_id: String) -> VoiceStateResponse {
        VoiceStateResponse {
            channel_id: None,
            deaf,
            guild_id: None,
            member: None,
            mute,
            request_to_speak_timestamp: None,
            suppress,
            self_stream: None,
            self_deaf,
            self_mute,
            self_video,
            session_id,
            user_id,
        }
    }
}

