/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookSlackEmbed {
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "title_link", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title_link: Option<Option<String>>,
    #[serde(rename = "text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub text: Option<Option<String>>,
    #[serde(rename = "color", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub color: Option<Option<String>>,
    #[serde(rename = "ts", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ts: Option<Option<i32>>,
    #[serde(rename = "pretext", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pretext: Option<Option<String>>,
    #[serde(rename = "footer", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub footer: Option<Option<String>>,
    #[serde(rename = "footer_icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub footer_icon: Option<Option<String>>,
    #[serde(rename = "author_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_name: Option<Option<String>>,
    #[serde(rename = "author_link", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_link: Option<Option<String>>,
    #[serde(rename = "author_icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_icon: Option<Option<String>>,
    #[serde(rename = "image_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<Option<String>>,
    #[serde(rename = "thumb_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub thumb_url: Option<Option<String>>,
    #[serde(rename = "fields", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub fields: Option<Option<Vec<models::WebhookSlackEmbedField>>>,
}

impl WebhookSlackEmbed {
    pub fn new() -> WebhookSlackEmbed {
        WebhookSlackEmbed {
            title: None,
            title_link: None,
            text: None,
            color: None,
            ts: None,
            pretext: None,
            footer: None,
            footer_icon: None,
            author_name: None,
            author_link: None,
            author_icon: None,
            image_url: None,
            thumb_url: None,
            fields: None,
        }
    }
}

