/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookSlackEmbedField {
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<String>>,
    #[serde(rename = "inline", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub inline: Option<Option<bool>>,
}

impl WebhookSlackEmbedField {
    pub fn new() -> WebhookSlackEmbedField {
        WebhookSlackEmbedField {
            name: None,
            value: None,
            inline: None,
        }
    }
}

