/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WelcomeMessageResponse {
    #[serde(rename = "author_ids")]
    pub author_ids: Vec<String>,
    #[serde(rename = "message")]
    pub message: String,
}

impl WelcomeMessageResponse {
    pub fn new(author_ids: Vec<String>, message: String) -> WelcomeMessageResponse {
        WelcomeMessageResponse {
            author_ids,
            message,
        }
    }
}

