/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WelcomeScreenPatchRequestPartial {
    #[serde(rename = "description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub description: Option<Option<String>>,
    #[serde(rename = "welcome_channels", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub welcome_channels: Option<Option<Vec<models::GuildWelcomeChannel>>>,
    #[serde(rename = "enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<Option<bool>>,
}

impl WelcomeScreenPatchRequestPartial {
    pub fn new() -> WelcomeScreenPatchRequestPartial {
        WelcomeScreenPatchRequestPartial {
            description: None,
            welcome_channels: None,
            enabled: None,
        }
    }
}

