/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetSettingsResponse {
    #[serde(rename = "enabled")]
    pub enabled: bool,
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
}

impl WidgetSettingsResponse {
    pub fn new(enabled: bool) -> WidgetSettingsResponse {
        WidgetSettingsResponse {
            enabled,
            channel_id: None,
        }
    }
}

