/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetMember {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "discriminator", deserialize_with = "Option::deserialize")]
    pub discriminator: Option<String>,
    #[serde(rename = "avatar", skip_serializing_if = "Option::is_none")]
    pub avatar: Option<models::Null>,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "avatar_url")]
    pub avatar_url: String,
    #[serde(rename = "activity", skip_serializing_if = "Option::is_none")]
    pub activity: Option<Box<models::WidgetActivity>>,
    #[serde(rename = "deaf", skip_serializing_if = "Option::is_none")]
    pub deaf: Option<bool>,
    #[serde(rename = "mute", skip_serializing_if = "Option::is_none")]
    pub mute: Option<bool>,
    #[serde(rename = "self_deaf", skip_serializing_if = "Option::is_none")]
    pub self_deaf: Option<bool>,
    #[serde(rename = "self_mute", skip_serializing_if = "Option::is_none")]
    pub self_mute: Option<bool>,
    #[serde(rename = "suppress", skip_serializing_if = "Option::is_none")]
    pub suppress: Option<bool>,
    #[serde(rename = "channel_id", skip_serializing_if = "Option::is_none")]
    pub channel_id: Option<String>,
}

impl WidgetMember {
    pub fn new(id: String, username: String, discriminator: Option<String>, status: String, avatar_url: String) -> WidgetMember {
        WidgetMember {
            id,
            username,
            discriminator,
            avatar: None,
            status,
            avatar_url,
            activity: None,
            deaf: None,
            mute: None,
            self_deaf: None,
            self_mute: None,
            suppress: None,
            channel_id: None,
        }
    }
}

