/*
 * Discord HTTP API (Preview)
 *
 * Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.
 *
 * The version of the OpenAPI document: 10
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WidgetResponse {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "instant_invite", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instant_invite: Option<Option<String>>,
    #[serde(rename = "channels")]
    pub channels: Vec<models::WidgetChannel>,
    #[serde(rename = "members")]
    pub members: Vec<models::WidgetMember>,
    #[serde(rename = "presence_count")]
    pub presence_count: i32,
}

impl WidgetResponse {
    pub fn new(id: String, name: String, channels: Vec<models::WidgetChannel>, members: Vec<models::WidgetMember>, presence_count: i32) -> WidgetResponse {
        WidgetResponse {
            id,
            name,
            instant_invite: None,
            channels,
            members,
            presence_count,
        }
    }
}

